'use client'

/**
 * PixelFrame — CSS 9-slice pack-frame shell around DOM card content
 * (T3, spec §9.2: "pixel shell, legible interior").
 *
 * Three themes, one contract:
 *   parchment — Harvestholm surfaces (codex, retros, memory, mailbox)
 *   slate     — Lantern Quay surfaces (outcomes, cargo, deploys, default)
 *   heavy     — the killswitch confirm dialog ONLY (the unadorned frame
 *               appears nowhere else — reserved-salience law)
 *
 * Asset resolution (manifest doctrine — no URL is ever constructed from
 * anything but a manifest row's path):
 *   1. `ui/frame_<theme>`          — the LimeZu Modern UI pack frame
 *                                    (32x32 family; T4 install lands these)
 *   2. `ui/frame_interim_<theme>`  — own-pixel 16-grid interim 9-slice
 *                                    (generated by world-compose-portraits.py
 *                                    --frames; placeholder doctrine)
 *   3. plain DOM border fallback   — loud (data-frame="fallback"), never
 *                                    silent-broken.
 *
 * The frame is SKIN: WHAT/NOW/PROOF content, honesty contract, and text-as-
 * text law are untouched by this wrapper.
 */
import { useEffect, useState } from 'react'
import { ASSET_BASE, type WorldAssetManifest } from '@/lib/world/sprites'

export type FrameTheme = 'parchment' | 'slate' | 'heavy'

/** Interior fill per theme (legibility ≥4.5:1 with zinc-100/900 text). */
const THEME_FILL: Record<FrameTheme, string> = {
  parchment: 'rgba(46, 36, 24, 0.96)',
  slate: 'rgba(24, 30, 38, 0.96)',
  heavy: 'rgba(20, 16, 16, 0.98)',
}

let manifestPromise: Promise<WorldAssetManifest | null> | null = null
function loadManifest(): Promise<WorldAssetManifest | null> {
  if (!manifestPromise) {
    manifestPromise = fetch(ASSET_BASE + 'manifest.json')
      .then((r) => (r.ok ? (r.json() as Promise<WorldAssetManifest>) : null))
      .catch(() => null)
  }
  return manifestPromise
}

/** Resolve the frame row for a theme: pack first, interim second. */
export function frameRowId(
  manifest: WorldAssetManifest | null,
  theme: FrameTheme
): { id: string; path: string; border: number } | null {
  if (!manifest?.assets) return null
  for (const id of [`ui/frame_${theme}`, `ui/frame_interim_${theme}`, 'ui/frame_interim']) {
    const row = manifest.assets.find((r) => r.id === id)
    if (row) {
      // `slice` = border-image-slice px, recorded on the manifest row by
      // world-compose-portraits.py (pack frames ship pre-upscaled ×2 NN so
      // slice px == rendered border px — integer only, no fractional pixel
      // scaling; typography/pixel law). Interim rows fall back to the grid.
      const slice = (row as { slice?: number }).slice
      return { id: row.id, path: row.path, border: slice || row.grid || 16 }
    }
  }
  return null
}

export default function PixelFrame({
  theme = 'slate',
  className = '',
  children,
}: {
  theme?: FrameTheme
  className?: string
  children: React.ReactNode
}) {
  const [frame, setFrame] = useState<{ id: string; path: string; border: number } | null>(null)
  const [resolved, setResolved] = useState(false)
  useEffect(() => {
    let alive = true
    loadManifest().then((m) => {
      if (!alive) return
      setFrame(frameRowId(m, theme))
      setResolved(true)
    })
    return () => {
      alive = false
    }
  }, [theme])

  if (!frame) {
    // Loud fallback: still a legible card, visibly frameless (placeholder
    // doctrine — a missing frame asset is a badge, not a broken dialog).
    return (
      <div
        data-frame={resolved ? 'fallback' : 'loading'}
        className={
          'rounded-lg border border-zinc-700 bg-zinc-900/95 text-zinc-100 shadow-2xl ' +
          className
        }
      >
        {children}
      </div>
    )
  }
  const b = frame.border * 2 // ×2 integer upscale for crispness at dashboard zoom
  return (
    <div
      data-frame={frame.id}
      className={'text-zinc-100 shadow-2xl ' + className}
      style={{
        borderStyle: 'solid',
        borderWidth: b,
        borderImageSource: `url(${ASSET_BASE}${frame.path})`,
        borderImageSlice: `${frame.border} fill`,
        borderImageWidth: `${b}px`,
        borderImageRepeat: 'repeat',
        imageRendering: 'pixelated',
        backgroundColor: THEME_FILL[theme],
        backgroundClip: 'padding-box',
      }}
    >
      {children}
    </div>
  )
}
