slug: cos
title: Chief of Staff
status: active
charter: Coordinate
capabilities: []
authority_level: elevated
created_at: '2026-05-26T09:16:04.559271+00:00'
updated_at: '2026-05-26T09:16:04.559286+00:00'
