#!/bin/bash
# bootstrap-roles.sh — seed the active officer roster into org_roles + instance/roles/active/
#
# Without this, mission compilation fails:
#   $ python3 cabinet/scripts/org-runtime.py roles list --product-slug X
#   []
#   $ ... outcome compile ...
#   unknown role for X: cos
#
# The cabinet has THREE places where role definitions live:
#   1. presets/<preset>/agents/<slug>.md     (Claude Code agent definitions,
#                                             copied to .claude/agents by
#                                             sync-agents.sh; instance/agents/
#                                             overlays for generated roles)
#   2. instance/roles/active/<slug>.yml      (durable role config + lineage
#                                             pointer; read by notify-officer,
#                                             captain-rule-encoder broadcast,
#                                             watchdog, etc.)
#   3. org_roles table in cabinet/cache/org-runtime.sqlite3 (Store ledger;
#                                             read by mission compiler when
#                                             assigning work-graph nodes)
#
# sync-agents.sh handles (1). This script handles (2) and (3). Idempotent:
# if a role is already seeded in either surface, this leaves it alone.
#
# ROSTER SOURCE — two paths:
#   default            the built-in 5-officer functional seed (work preset:
#                      cos/cto/cpo/cro/coo). Unchanged behavior.
#   --roster <yml>     PORTFOLIO PATH: seed the roster declared in an
#                      instance config file (e.g. instance/config/hq-instance.yml)
#                      instead of the built-in seed. The file must carry a
#                      top-level `roster:` block; per role (2-space key,
#                      4-space fields):
#                        roster:
#                          cos:
#                            title: Chair
#                            model: claude-fable-5
#                            capabilities: [cap1, cap2]
#                            authority_level: captain_proxy
#                      Unknown per-role keys (type:, telegram:, …) are
#                      ignored here — they belong to other consumers.
#
# Usage:
#   bash cabinet/scripts/bootstrap-roles.sh                       # uses active product slug
#   bash cabinet/scripts/bootstrap-roles.sh --product-slug X      # explicit override
#   bash cabinet/scripts/bootstrap-roles.sh --roster instance/config/hq-instance.yml

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CABINET_ROOT="${CABINET_ROOT:-$(cd "$SCRIPT_DIR/../.." && pwd)}"
export CABINET_ROOT

# Read active product slug from instance/config/active-project.txt unless
# overridden via --product-slug.
PRODUCT_SLUG=""
ROSTER_FILE=""
while [ $# -gt 0 ]; do
  case "$1" in
    --product-slug) PRODUCT_SLUG="$2"; shift 2 ;;
    --product-slug=*) PRODUCT_SLUG="${1#--product-slug=}"; shift ;;
    --roster) ROSTER_FILE="$2"; shift 2 ;;
    --roster=*) ROSTER_FILE="${1#--roster=}"; shift ;;
    -h|--help)
      sed -n '1,48p' "$0" | sed 's/^# \{0,1\}//' >&2
      exit 0
      ;;
    *) echo "[bootstrap-roles] unknown arg: $1" >&2; exit 2 ;;
  esac
done

if [ -n "$ROSTER_FILE" ] && [ ! -f "$ROSTER_FILE" ]; then
  echo "[bootstrap-roles] --roster file not found: $ROSTER_FILE" >&2
  exit 2
fi

if [ -z "$PRODUCT_SLUG" ]; then
  ACTIVE_PROJECT_FILE="$CABINET_ROOT/instance/config/active-project.txt"
  if [ -f "$ACTIVE_PROJECT_FILE" ]; then
    PRODUCT_SLUG="$(tr -d '[:space:]' < "$ACTIVE_PROJECT_FILE")"
  fi
fi
if [ -z "$PRODUCT_SLUG" ]; then
  echo "[bootstrap-roles] no product slug — pass --product-slug or set instance/config/active-project.txt" >&2
  exit 1
fi

echo "[bootstrap-roles] product_slug=$PRODUCT_SLUG"
echo "[bootstrap-roles] CABINET_ROOT=$CABINET_ROOT"

# -----------------------------------------------------------------------------
# Role definitions — the 5 active officers + per-slug capabilities/authority.
# Capabilities mirror cabinet/officer-capabilities.conf where overlap exists;
# the slugs are the canonical set referenced by the mission compiler.
# -----------------------------------------------------------------------------

ACTIVE_DIR="$CABINET_ROOT/instance/roles/active"
mkdir -p "$ACTIVE_DIR"

seed_role() {
  local slug="$1" title="$2" model="$3" caps="$4" auth="$5"

  # ---- (2) instance/roles/active/<slug>.yml ----
  local yml="$ACTIVE_DIR/$slug.yml"
  if [ -f "$yml" ]; then
    echo "[bootstrap-roles] $slug: instance/roles/active/$slug.yml already present, skipping"
  else
    cat > "$yml" <<EOF
# instance/roles/active/$slug.yml — generated by bootstrap-roles.sh
# Captain-overridable; edit freely. Lineage tracked in org_roles + role_*
# events; this file is the operational view.
slug: $slug
title: $title
product_slug: $PRODUCT_SLUG
status: active
model: $model
authority_level: $auth
capabilities:
$(echo "$caps" | tr ',' '\n' | sed 's/^/  - /')
hats: []
created_at: $(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF
    echo "[bootstrap-roles] $slug: wrote $yml"
  fi

  # ---- (3) org_roles table ----
  # Use the org_runtime.py CLI — emits the proper role.defined event +
  # writes to the Store SQLite. Idempotent on duplicate slug per the CLI.
  local exists
  exists="$(python3 "$CABINET_ROOT/cabinet/scripts/org-runtime.py" roles show \
    --product-slug "$PRODUCT_SLUG" --role "$slug" 2>/dev/null || true)"
  if [ -n "$exists" ] && [ "$exists" != "null" ]; then
    echo "[bootstrap-roles] $slug: org_roles row already present, skipping"
    return 0
  fi

  # Build --capability args (one flag per capability — CLI takes single value).
  local cap_args=()
  local IFS=','
  for c in $caps; do
    cap_args+=(--capability "$c")
  done
  unset IFS

  if python3 "$CABINET_ROOT/cabinet/scripts/org-runtime.py" roles define \
      --product-slug "$PRODUCT_SLUG" \
      --role "$slug" \
      --name "$title" \
      --charter "Bootstrap charter for $title. Refine via Captain ratification + role evolution proposals." \
      --authority-level "$auth" \
      "${cap_args[@]}" \
      --state active \
      --actor bootstrap-roles.sh \
      >/dev/null 2>&1; then
    echo "[bootstrap-roles] $slug: org_roles row created"
  else
    echo "[bootstrap-roles] WARN $slug: org_runtime.py roles define failed (run manually to debug)"
  fi
}

if [ -n "$ROSTER_FILE" ]; then
  # ---- PORTFOLIO PATH: roster-driven seed from instance config ----
  # awk emits one TAB-separated line per role: slug \t title \t model \t
  # caps(csv) \t authority. Same fixed-indent walking style as
  # load-preset.sh's list_hired_agents / peers.yml validator: top-level
  # `roster:` opens the section; any other top-level key closes it;
  # 2-space keys are role slugs; 4-space `key: value` lines are fields.
  echo "[bootstrap-roles] roster file: $ROSTER_FILE"
  ROSTER_TSV=$(awk '
    function emit() {
      if (slug != "") printf "%s\t%s\t%s\t%s\t%s\n", slug, title, model, caps, auth
    }
    /^roster:[[:space:]]*$/ { section = 1; next }
    /^[A-Za-z_#-]/          { if (section && slug != "") { emit(); slug = "" } ; section = 0 }
    section && /^  [a-z0-9][a-z0-9-]*:[[:space:]]*$/ {
      emit()
      slug = $0; sub(/^  /, "", slug); sub(/:.*$/, "", slug)
      title = ""; model = ""; caps = ""; auth = ""
      next
    }
    section && slug != "" && /^    [a-z_]+:/ {
      line = $0; sub(/^    /, "", line)
      key = line; sub(/:.*$/, "", key)
      val = line; sub(/^[a-z_]+:[[:space:]]*/, "", val)
      sub(/[[:space:]]*(#.*)?$/, "", val)        # strip trailing comment
      gsub(/^"|"$/, "", val)
      if (key == "title")            title = val
      else if (key == "model")       model = val
      else if (key == "authority_level") auth = val
      else if (key == "capabilities") {
        gsub(/[\[\]]/, "", val); gsub(/[[:space:]]/, "", val)
        caps = val
      }
      # unknown keys (type:, telegram:, …) intentionally ignored
    }
    END { emit() }
  ' "$ROSTER_FILE")

  if [ -z "$ROSTER_TSV" ]; then
    echo "[bootstrap-roles] no roles found under 'roster:' in $ROSTER_FILE" >&2
    exit 2
  fi

  while IFS=$'\t' read -r slug title model caps auth; do
    [ -z "$slug" ] && continue
    if [ -z "$title" ] || [ -z "$model" ] || [ -z "$caps" ] || [ -z "$auth" ]; then
      echo "[bootstrap-roles] roster role '$slug' missing required field(s) — need title/model/capabilities/authority_level (got title='$title' model='$model' capabilities='$caps' authority_level='$auth')" >&2
      exit 2
    fi
    seed_role "$slug" "$title" "$model" "$caps" "$auth"
  done <<< "$ROSTER_TSV"
else
  # ---- DEFAULT PATH: built-in functional seed (unchanged) ----
  # Officer slug | Title                       | Model               | Capabilities                                                                                | Authority level
  seed_role cos "Chief of Staff"               claude-fable-5       "logs_captain_decisions,reviews_specs,reviews_implementations,validates_deployments"        captain_proxy
  seed_role cto "Chief Technology Officer"     claude-fable-5       "deploys_code,reviews_implementations,engineering_execution"                                 mission_executor
  seed_role cpo "Chief Product Officer"        claude-fable-5       "reviews_specs,product_strategy,backlog_management"                                          mission_executor
  seed_role cro "Chief Research Officer"       claude-sonnet-4-6    "reviews_research,market_intelligence,research_sweep"                                        mission_executor
  seed_role coo "Chief Operating Officer"      claude-sonnet-4-6    "validates_deployments,operational_health,quality_gate"                                      mission_executor
fi

echo "[bootstrap-roles] done. Verify:"
echo "  python3 cabinet/scripts/org-runtime.py roles list --product-slug $PRODUCT_SLUG"
echo "  ls $ACTIVE_DIR"
