#!/bin/bash
# bootstrap-roles.sh — seed the 5 active officers into org_roles + instance/roles/active/
#
# Without this, mission compilation fails:
#   $ python3 cabinet/scripts/org-runtime.py roles list --product-slug X
#   []
#   $ ... outcome compile ...
#   unknown role for X: cos
#
# The cabinet has THREE places where role definitions live:
#   1. presets/work/agents/<slug>.md         (Claude Code agent definitions,
#                                             copied to .claude/agents by
#                                             sync-agents.sh)
#   2. instance/roles/active/<slug>.yml      (durable role config + lineage
#                                             pointer; read by notify-officer,
#                                             captain-rule-encoder broadcast,
#                                             watchdog, etc.)
#   3. org_roles table in cabinet/cache/org-runtime.sqlite3 (Store ledger;
#                                             read by mission compiler when
#                                             assigning work-graph nodes)
#
# sync-agents.sh handles (1). This script handles (2) and (3). Idempotent:
# if a role is already seeded in either surface, this leaves it alone.
#
# Usage:
#   bash cabinet/scripts/bootstrap-roles.sh                       # uses active product slug
#   bash cabinet/scripts/bootstrap-roles.sh --product-slug X      # explicit override

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CABINET_ROOT="${CABINET_ROOT:-$(cd "$SCRIPT_DIR/../.." && pwd)}"
export CABINET_ROOT

# Read active product slug from instance/config/active-project.txt unless
# overridden via --product-slug.
PRODUCT_SLUG=""
while [ $# -gt 0 ]; do
  case "$1" in
    --product-slug) PRODUCT_SLUG="$2"; shift 2 ;;
    --product-slug=*) PRODUCT_SLUG="${1#--product-slug=}"; shift ;;
    -h|--help)
      sed -n '1,30p' "$0" | sed 's/^# \{0,1\}//' >&2
      exit 0
      ;;
    *) echo "[bootstrap-roles] unknown arg: $1" >&2; exit 2 ;;
  esac
done

if [ -z "$PRODUCT_SLUG" ]; then
  ACTIVE_PROJECT_FILE="$CABINET_ROOT/instance/config/active-project.txt"
  if [ -f "$ACTIVE_PROJECT_FILE" ]; then
    PRODUCT_SLUG="$(tr -d '[:space:]' < "$ACTIVE_PROJECT_FILE")"
  fi
fi
if [ -z "$PRODUCT_SLUG" ]; then
  echo "[bootstrap-roles] no product slug — pass --product-slug or set instance/config/active-project.txt" >&2
  exit 1
fi

echo "[bootstrap-roles] product_slug=$PRODUCT_SLUG"
echo "[bootstrap-roles] CABINET_ROOT=$CABINET_ROOT"

# -----------------------------------------------------------------------------
# Role definitions — the 5 active officers + per-slug capabilities/authority.
# Capabilities mirror cabinet/officer-capabilities.conf where overlap exists;
# the slugs are the canonical set referenced by the mission compiler.
# -----------------------------------------------------------------------------

ACTIVE_DIR="$CABINET_ROOT/instance/roles/active"
mkdir -p "$ACTIVE_DIR"

seed_role() {
  local slug="$1" title="$2" model="$3" caps="$4" auth="$5"

  # ---- (2) instance/roles/active/<slug>.yml ----
  local yml="$ACTIVE_DIR/$slug.yml"
  if [ -f "$yml" ]; then
    echo "[bootstrap-roles] $slug: instance/roles/active/$slug.yml already present, skipping"
  else
    cat > "$yml" <<EOF
# instance/roles/active/$slug.yml — generated by bootstrap-roles.sh
# Captain-overridable; edit freely. Lineage tracked in org_roles + role_*
# events; this file is the operational view.
slug: $slug
title: $title
product_slug: $PRODUCT_SLUG
status: active
model: $model
authority_level: $auth
capabilities:
$(echo "$caps" | tr ',' '\n' | sed 's/^/  - /')
hats: []
created_at: $(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF
    echo "[bootstrap-roles] $slug: wrote $yml"
  fi

  # ---- (3) org_roles table ----
  # Use the org_runtime.py CLI — emits the proper role.defined event +
  # writes to the Store SQLite. Idempotent on duplicate slug per the CLI.
  local exists
  exists="$(python3 "$CABINET_ROOT/cabinet/scripts/org-runtime.py" roles show \
    --product-slug "$PRODUCT_SLUG" --role "$slug" 2>/dev/null || true)"
  if [ -n "$exists" ] && [ "$exists" != "null" ]; then
    echo "[bootstrap-roles] $slug: org_roles row already present, skipping"
    return 0
  fi

  # Build --capability args (one flag per capability — CLI takes single value).
  local cap_args=()
  local IFS=','
  for c in $caps; do
    cap_args+=(--capability "$c")
  done
  unset IFS

  if python3 "$CABINET_ROOT/cabinet/scripts/org-runtime.py" roles define \
      --product-slug "$PRODUCT_SLUG" \
      --role "$slug" \
      --name "$title" \
      --charter "Bootstrap charter for $title. Refine via Captain ratification + role evolution proposals." \
      --authority-level "$auth" \
      "${cap_args[@]}" \
      --state active \
      --actor bootstrap-roles.sh \
      >/dev/null 2>&1; then
    echo "[bootstrap-roles] $slug: org_roles row created"
  else
    echo "[bootstrap-roles] WARN $slug: org_runtime.py roles define failed (run manually to debug)"
  fi
}

# Officer slug | Title                       | Model               | Capabilities                                                                                | Authority level
seed_role cos "Chief of Staff"               claude-opus-4-7      "logs_captain_decisions,reviews_specs,reviews_implementations,validates_deployments"        captain_proxy
seed_role cto "Chief Technology Officer"     claude-opus-4-7      "deploys_code,reviews_implementations,engineering_execution"                                 mission_executor
seed_role cpo "Chief Product Officer"        claude-opus-4-7      "reviews_specs,product_strategy,backlog_management"                                          mission_executor
seed_role cro "Chief Research Officer"       claude-sonnet-4-6    "reviews_research,market_intelligence,research_sweep"                                        mission_executor
seed_role coo "Chief Operating Officer"      claude-sonnet-4-6    "validates_deployments,operational_health,quality_gate"                                      mission_executor

echo "[bootstrap-roles] done. Verify:"
echo "  python3 cabinet/scripts/org-runtime.py roles list --product-slug $PRODUCT_SLUG"
echo "  ls $ACTIVE_DIR"
