#!/usr/bin/env bash
# check-layer-separation.sh — FINAL-C CI gate enforcing three-layer Cabinet
# dependency direction:
#
#   framework/  →  cannot reference  instance/  or  presets/
#   presets/    →  cannot import code from  instance/  (path-string overlay refs OK)
#   instance/   →  may reference anything
#
# This script is a **baseline-ratchet** gate, not a hard-fail. Known
# violations live in TWO tracked files, split by class (egg plan R034):
#
#   .layer-separation-baseline  — SHRINK-ONLY DEBT: couplings scheduled for
#       cleanup. Machine-regenerated by `--update-baseline`; only ratchets
#       down.
#   .layer-separation-allowlist — BY-DESIGN: framework reading Captain-owned
#       instance CONFIG (posture / grants / act-first / standing-pull).
#       Hand-curated + documented in-file; never machine-rewritten.
#
# CI exits 0 when the live violation set is a subset of baseline ∪ allowlist,
# and exits 1 on any new violation outside both. Growing EITHER file requires
# Captain approval; `--update-baseline` rewrites the baseline to the current
# violation set MINUS the allowlist (cleanup PRs ratchet the debt down).
#
# Detection rules (Python files only; .md / .yml / docstrings excluded):
#
#   framework/**/*.py
#     - `import instance` / `from instance ...` / `import presets` /
#       `from presets ...`  →  HARD violation (cannot exist in valid Python
#       anyway; included for defense-in-depth).
#     - String literals `"instance"` or `'instance'` or `"presets"` /
#       `'presets'` used in `Path(...) / "instance" / ...` style runtime
#       coupling  →  violation.
#     - (SRC-5, source-adapter seam) `import`/`from` of a screenpipe `_shared`
#       lib (draft_lib | commitments_lib | context_lib | me_signal | sp_lib |
#       product_ops_lib | email_lib | teams_graph_lib | agent_reasoning)  →
#       violation; and a runtime `~/.screenpipe` / `".screenpipe"` /
#       `screenpipe-brain` / `OBSIDIAN_VAULT` PATH literal  →  violation.
#       framework CORE reaches the captain's estate only through
#       framework.sources.get_source(); the adapter naming screenpipe lives in
#       instance/flavor-a/. tests/ + the sources/ seam are excluded (strong
#       sibling: framework/tests/test_no_screenpipe_in_core.py).
#
#   presets/**/*.py
#     - `import instance` / `from instance ...`  →  violation.
#     - String literal `"instance"` path components in `Path(...) / "instance"`
#       constructions are ALLOWED (overlay convention — presets can describe
#       where instance overlays live without taking a code dep).
#
# Comments (`# ...`), CLI help strings, and docstring text are excluded by
# checking that the offending token is not within a `#` comment or inside a
# triple-quoted block. We approximate the latter cheaply by ignoring lines
# whose stripped-content begins or ends with `"""`/`'''`.
#
# Usage:
#   bash cabinet/scripts/check-layer-separation.sh            # CI mode: exit 1 on new
#   bash cabinet/scripts/check-layer-separation.sh --report   # print all violations, exit 0
#   bash cabinet/scripts/check-layer-separation.sh --update-baseline
#                                                             # rewrite DEBT baseline to
#                                                             # current set minus allowlist
#
# Both files share the format — one violation per line:
#   <path>:<rule_id>
# where <rule_id> is one of:
#   FRAMEWORK_IMPORTS_INSTANCE, FRAMEWORK_IMPORTS_PRESETS,
#   FRAMEWORK_PATH_INSTANCE,    FRAMEWORK_PATH_PRESETS,
#   FRAMEWORK_IMPORTS_PERSONAL_SOURCE, FRAMEWORK_PATH_PERSONAL_SOURCE,
#   PRESETS_IMPORTS_INSTANCE
# The allowlist may carry ONLY FRAMEWORK_PATH_INSTANCE entries (config-read
# class); personal-source/import classes are never allowlistable (see the
# allowlist header + golden eval-021). The rule class name is adapter-
# agnostic; today's one concrete target is the screenpipe adapter.
# Line numbers are intentionally omitted so trivial file edits don't churn
# the baseline. The CI signal is "this file violates this rule" — once.

set -u
set -o pipefail

# Resolve repo root (this script lives at cabinet/scripts/).
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
BASELINE_FILE="${REPO_ROOT}/.layer-separation-baseline"
ALLOWLIST_FILE="${REPO_ROOT}/.layer-separation-allowlist"

MODE="check"
case "${1:-}" in
  --report) MODE="report" ;;
  --update-baseline) MODE="update" ;;
  --help|-h)
    sed -n '2,40p' "$0"
    exit 0
    ;;
  "") ;;
  *)
    echo "[layer-sep] unknown arg: $1" >&2
    exit 2
    ;;
esac

# Collect violations into a sorted, deduped list of "path:rule_id".
# We scan with grep -nE and post-filter in awk to:
#   1) drop lines whose leading non-space character is `#`
#   2) drop lines that look like docstring delimiters
#   3) emit "path:rule_id" (line number stripped for stable baselines)
collect_violations() {
  local out
  out="$(mktemp)"

  # Run greps from inside REPO_ROOT so paths come out repo-relative.
  # That keeps the baseline portable across worktrees / CI checkouts.
  cd "$REPO_ROOT" || { rm -f "$out"; return 1; }

  # Rule: framework imports
  if [ -d "framework" ]; then
    grep -rnE '^[[:space:]]*(import|from)[[:space:]]+instance([[:space:]\.]|$)' \
         framework --include="*.py" 2>/dev/null \
      | awk -F: '{ path=$1; sub(/^[[:space:]]*/, "", $3); if ($3 !~ /^#/) print path ":FRAMEWORK_IMPORTS_INSTANCE" }' \
      >> "$out"

    grep -rnE '^[[:space:]]*(import|from)[[:space:]]+presets([[:space:]\.]|$)' \
         framework --include="*.py" 2>/dev/null \
      | awk -F: '{ path=$1; sub(/^[[:space:]]*/, "", $3); if ($3 !~ /^#/) print path ":FRAMEWORK_IMPORTS_PRESETS" }' \
      >> "$out"

    # Rule: framework path-string coupling. We look for the literal quoted
    # token "instance" or 'instance' (and same for "presets") and only count
    # it when the line is NOT a comment AND NOT a CLI help string AND NOT a
    # docstring delimiter line. We rely on the cheap heuristic that runtime
    # coupling uses Path(...) / "instance" / ... — these appear at code
    # indentation, not inside triple-quoted blocks. Comments in tests + help
    # strings are filtered by the awk pass.
    grep -rnE "(\"instance\"|'instance')" \
         framework --include="*.py" 2>/dev/null \
      | awk -F: '{
          path=$1;
          # Reconstruct the source line (fields 3..NF) — F:N: split eats colons
          src="";
          for (i=3; i<=NF; i++) { src = (i==3 ? $i : src ":" $i) }
          stripped=src; sub(/^[[:space:]]+/, "", stripped);
          # Exclude pure comment lines and likely-docstring lines
          if (stripped ~ /^#/) next;
          if (stripped ~ /^"""/ || stripped ~ /^'\''\'\''\'\''/) next;
          # Exclude CLI help= strings (argparse) — overlay convention reference
          if (src ~ /help[[:space:]]*=/) next;
          print path ":FRAMEWORK_PATH_INSTANCE";
        }' \
      >> "$out"

    grep -rnE "(\"presets\"|'presets')" \
         framework --include="*.py" 2>/dev/null \
      | awk -F: '{
          path=$1;
          src="";
          for (i=3; i<=NF; i++) { src = (i==3 ? $i : src ":" $i) }
          stripped=src; sub(/^[[:space:]]+/, "", stripped);
          if (stripped ~ /^#/) next;
          if (stripped ~ /^"""/ || stripped ~ /^'\''\'\''\'\''/) next;
          if (src ~ /help[[:space:]]*=/) next;
          print path ":FRAMEWORK_PATH_PRESETS";
        }' \
      >> "$out"

    # Rule: framework imports of screenpipe `_shared` libs (SRC-5 — clean-room
    # SOURCE ratchet). A clean-room / Flavor-B box has no ~/.screenpipe, so
    # framework CORE must reach the captain's estate through
    # framework.sources.get_source(), never a `_shared` lib. tests/ and the
    # sources/ seam (which NAMES the Protocol + describes the Flavor-A mapping)
    # are excluded, matching framework/tests/test_no_screenpipe_in_core.py. The
    # baseline shrinks to empty as SRC-2..6 reroute each caller through the seam.
    grep -rnE '^[[:space:]]*(import|from)[[:space:]]+(draft_lib|commitments_lib|context_lib|me_signal|sp_lib|product_ops_lib|email_lib|teams_graph_lib|agent_reasoning)([[:space:]\.]|$)' \
         framework --include="*.py" --exclude-dir=tests --exclude-dir=sources \
         --exclude='test_*.py' --exclude='*_test.py' 2>/dev/null \
      | awk -F: '{ path=$1; sub(/^[[:space:]]*/, "", $3); if ($3 !~ /^#/) print path ":FRAMEWORK_IMPORTS_PERSONAL_SOURCE" }' \
      >> "$out"

    # Rule: framework runtime screenpipe PATH literals (SRC-5) — a ~/.screenpipe
    # or ".screenpipe" Path component, the screenpipe-brain vault dir, or the
    # OBSIDIAN_VAULT env key. Quote-anchored ("~/.screenpipe / ".screenpipe) so a
    # docstring/comment MENTION (the vendoring note in voice_charset.py, the
    # _shared/.env docstring in probes/runner.py) does not trip; the same
    # comment/docstring/help= awk filter as the INSTANCE path rule applies too.
    grep -rnE "([\"'](~/)?\.screenpipe|screenpipe-brain|OBSIDIAN_VAULT)" \
         framework --include="*.py" --exclude-dir=tests --exclude-dir=sources \
         --exclude='test_*.py' --exclude='*_test.py' 2>/dev/null \
      | awk -F: '{
          path=$1;
          src="";
          for (i=3; i<=NF; i++) { src = (i==3 ? $i : src ":" $i) }
          stripped=src; sub(/^[[:space:]]+/, "", stripped);
          if (stripped ~ /^#/) next;
          if (stripped ~ /^"""/ || stripped ~ /^'\''\'\''\'\''/) next;
          if (src ~ /help[[:space:]]*=/) next;
          print path ":FRAMEWORK_PATH_PERSONAL_SOURCE";
        }' \
      >> "$out"
  fi

  # Rule: presets imports of instance (path-string overlays are allowed).
  if [ -d "presets" ]; then
    grep -rnE '^[[:space:]]*(import|from)[[:space:]]+instance([[:space:]\.]|$)' \
         presets --include="*.py" 2>/dev/null \
      | awk -F: '{ path=$1; sub(/^[[:space:]]*/, "", $3); if ($3 !~ /^#/) print path ":PRESETS_IMPORTS_INSTANCE" }' \
      >> "$out"
  fi

  sort -u "$out"
  rm -f "$out"
}

violations="$(collect_violations)"
violation_count=0
if [ -n "$violations" ]; then
  violation_count="$(printf '%s\n' "$violations" | wc -l | tr -d ' ')"
fi

# BY-DESIGN allowlist (hand-curated; absent file = empty class). Same
# comment/blank stripping as the baseline read.
if [ -f "$ALLOWLIST_FILE" ]; then
  allowlist="$(sort -u "$ALLOWLIST_FILE" | grep -vE '^[[:space:]]*(#|$)' || true)"
else
  allowlist=""
fi
allowlist_count=0
if [ -n "$allowlist" ]; then
  allowlist_count="$(printf '%s\n' "$allowlist" | wc -l | tr -d ' ')"
fi

case "$MODE" in
  report)
    if [ -z "$violations" ]; then
      echo "[layer-sep] CLEAN — no cross-layer violations detected."
      exit 0
    fi
    echo "[layer-sep] ${violation_count} violation(s):"
    printf '%s\n' "$violations" | sed 's/^/  /'
    exit 0
    ;;

  update)
    # Rewrite the DEBT baseline to match current state MINUS the BY-DESIGN
    # allowlist. Intended for cleanup PRs that remove violations — running
    # this in a PR that ADDS violations would be caught at review (baseline
    # diff is a +N change; growing it requires Captain approval). The
    # curated by-design documentation lives in the allowlist file, so this
    # regeneration loses nothing.
    debt="$violations"
    if [ -n "$violations" ] && [ -n "$allowlist" ]; then
      debt="$(comm -23 \
        <(printf '%s\n' "$violations") \
        <(printf '%s\n' "$allowlist"))"
    fi
    debt_count=0
    if [ -n "$debt" ]; then
      debt_count="$(printf '%s\n' "$debt" | wc -l | tr -d ' ')"
    fi
    {
      printf '%s\n' \
        '# Layer-separation baseline — SHRINK-ONLY DEBT ledger (machine-regenerated).' \
        '#' \
        '# One `<path>:<rule_id>` per line: a known cross-layer violation that is' \
        '# DEBT, scheduled for cleanup — this list only ratchets DOWN. CI (check' \
        '# mode) fails on any violation not listed here AND not in the BY-DESIGN' \
        '# allowlist (.layer-separation-allowlist — hand-curated, Captain-ratified' \
        '# instance-config reads; see that file for the class definition).' \
        '#' \
        '# Regenerate after a cleanup PR:' \
        '#   bash cabinet/scripts/check-layer-separation.sh --update-baseline' \
        '# (writes current violations MINUS the allowlist; a diff that GROWS this' \
        '# file requires Captain approval). Rule ids: check-layer-separation.sh.'
      if [ -n "$debt" ]; then
        printf '%s\n' "$debt"
      fi
    } > "$BASELINE_FILE"
    echo "[layer-sep] baseline rewritten with ${debt_count} debt entries (${allowlist_count} by-design entries live in the allowlist) → ${BASELINE_FILE}"
    exit 0
    ;;

  check)
    if [ ! -f "$BASELINE_FILE" ]; then
      echo "[layer-sep] WARNING: ${BASELINE_FILE} missing — treating empty baseline." >&2
      baseline=""
    else
      baseline="$(sort -u "$BASELINE_FILE" | grep -vE '^[[:space:]]*(#|$)' || true)"
    fi

    # Accepted set = baseline (debt) ∪ allowlist (by-design).
    accepted="$baseline"
    if [ -n "$allowlist" ]; then
      accepted="$(printf '%s\n%s\n' "$baseline" "$allowlist" | grep -v '^$' | sort -u)"
    fi

    # New violations = current minus accepted.
    new_violations="$(comm -23 \
      <(printf '%s\n' "$violations") \
      <(printf '%s\n' "$accepted"))"

    # Removed violations = DEBT baseline minus current (informational only —
    # the ratchet-down signal; allowlist entries are permanent-by-design and
    # excluded from this signal).
    fixed_violations="$(comm -13 \
      <(printf '%s\n' "$violations") \
      <(printf '%s\n' "$baseline"))"

    # Allowlist entries no longer detected (informational — prune by hand).
    stale_allowlist=""
    if [ -n "$allowlist" ]; then
      stale_allowlist="$(comm -13 \
        <(printf '%s\n' "$violations") \
        <(printf '%s\n' "$allowlist"))"
    fi

    new_count=0
    if [ -n "$new_violations" ]; then
      new_count="$(printf '%s\n' "$new_violations" | wc -l | tr -d ' ')"
    fi
    fixed_count=0
    if [ -n "$fixed_violations" ]; then
      fixed_count="$(printf '%s\n' "$fixed_violations" | wc -l | tr -d ' ')"
    fi

    baseline_count=0
    if [ -n "$baseline" ]; then
      baseline_count="$(printf '%s\n' "$baseline" | wc -l | tr -d ' ')"
    fi

    echo "[layer-sep] baseline=${baseline_count}  allowlist=${allowlist_count}  current=${violation_count}  new=${new_count}  fixed=${fixed_count}"

    if [ "$fixed_count" -gt 0 ]; then
      echo "[layer-sep] FIXED (run --update-baseline to ratchet down):"
      printf '%s\n' "$fixed_violations" | sed 's/^/  - /'
    fi

    if [ -n "$stale_allowlist" ]; then
      echo "[layer-sep] STALE ALLOWLIST entries no longer detected (prune .layer-separation-allowlist by hand):"
      printf '%s\n' "$stale_allowlist" | sed 's/^/  - /'
    fi

    if [ "$new_count" -gt 0 ]; then
      echo "[layer-sep] NEW VIOLATIONS (not in baseline or allowlist):" >&2
      printf '%s\n' "$new_violations" | sed 's/^/  + /' >&2
      echo "[layer-sep] FAIL — layer separation regressed. Either remove the" >&2
      echo "          violation; or, if it is ratchet-down DEBT, justify in PR and run" >&2
      echo "          \`bash cabinet/scripts/check-layer-separation.sh --update-baseline\`;" >&2
      echo "          or, if it is a Captain-ratified BY-DESIGN instance-config read," >&2
      echo "          add it to .layer-separation-allowlist with documentation." >&2
      echo "          (Captain approval required to grow either file.)" >&2
      exit 1
    fi

    echo "[layer-sep] OK — no new layer-separation violations."
    exit 0
    ;;
esac
