#!/usr/bin/env bash
# work-graph-complete.sh — officer marks a mission work-graph node as done/failed/verified
#
# Closes the mission loop the rebuild left open: officers can now record task
# completion from within their session, emitting a typed event to the ledger
# and (best-effort) updating the work_graph_nodes Postgres row.
#
# The mission compiler reads completion events when rebuilding the work graph
# at session start, so subsequent sessions see the up-to-date task statuses
# without per-session reset.
#
# Usage:
#   work-graph-complete.sh <node_id> [--status done|failed|verified] [--evidence FILE_OR_TEXT]
#   work-graph-complete.sh outcome-launch-mvp-task-003 --status done --evidence /tmp/api-deploy.log
#   work-graph-complete.sh outcome-x-task-001 --status failed --evidence "Tests red on PR #42"
#
# Resume signal:
#   Exit 0 + emitted event = success. Exit non-zero = failure (see stderr).
#
# Environment:
#   OFFICER_NAME       — actor for the emitted event (defaults to "system")
#   CABINET_ROOT       — repo root (defaults to script's two-levels-up)
#   DATABASE_URL       — if set, also UPDATEs work_graph_nodes row (best-effort)
#   CABINET_EVENT_LOG_DIR — event log target (defaults to ~/Library/Application Support/cabinet/events)

set -euo pipefail

# --- defaults ---
STATUS="done"
EVIDENCE=""
NODE_ID=""

usage() {
  cat <<'EOF' >&2
Usage: work-graph-complete.sh <node_id> [--status done|failed|verified] [--evidence FILE_OR_TEXT]

Records completion of a mission work-graph node.

Arguments:
  <node_id>                  Task ID in the form "<outcome_id>-task-NNN"

Options:
  --status done|failed|verified   Completion status (default: done)
  --evidence FILE_OR_TEXT         Path to evidence file, or inline evidence text
  -h, --help                      Show this help

Environment:
  OFFICER_NAME       Actor for the emitted event (default: "system")
  DATABASE_URL       If set, also updates work_graph_nodes row
EOF
}

# --- arg parsing ---
while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help)
      usage
      exit 0
      ;;
    --status)
      shift
      [[ $# -gt 0 ]] || { echo "work-graph-complete: --status requires a value" >&2; exit 2; }
      STATUS="$1"
      ;;
    --evidence)
      shift
      [[ $# -gt 0 ]] || { echo "work-graph-complete: --evidence requires a value" >&2; exit 2; }
      EVIDENCE="$1"
      ;;
    --status=*)
      STATUS="${1#--status=}"
      ;;
    --evidence=*)
      EVIDENCE="${1#--evidence=}"
      ;;
    --)
      shift
      ;;
    -*)
      echo "work-graph-complete: unknown flag: $1" >&2
      usage
      exit 2
      ;;
    *)
      if [[ -z "$NODE_ID" ]]; then
        NODE_ID="$1"
      else
        echo "work-graph-complete: unexpected positional arg: $1 (node_id already set to '$NODE_ID')" >&2
        exit 2
      fi
      ;;
  esac
  shift
done

# --- validate inputs ---
if [[ -z "$NODE_ID" ]]; then
  echo "work-graph-complete: <node_id> is required" >&2
  usage
  exit 2
fi

case "$STATUS" in
  done|failed|verified) ;;
  *)
    echo "work-graph-complete: invalid --status '$STATUS' (must be done|failed|verified)" >&2
    exit 2
    ;;
esac

# --- resolve outcome_id from node_id ---
# Task IDs are generated by _generate_task_id(outcome_id, index) as:
#   "{outcome_id}-task-{index:03d}"
# Split on "-task-" — take the head as outcome_id, tail as index.
if [[ "$NODE_ID" != *-task-* ]]; then
  echo "work-graph-complete: node_id '$NODE_ID' does not match '<outcome_id>-task-NNN' format" >&2
  exit 2
fi

OUTCOME_ID="${NODE_ID%-task-*}"
TASK_INDEX="${NODE_ID##*-task-}"

# --- resolve evidence ---
EVIDENCE_TEXT=""
EVIDENCE_PATH=""
if [[ -n "$EVIDENCE" ]]; then
  if [[ -f "$EVIDENCE" ]]; then
    EVIDENCE_PATH="$EVIDENCE"
    # Read up to first 8 KB to keep event payloads compact
    EVIDENCE_TEXT="$(head -c 8192 "$EVIDENCE" 2>/dev/null || true)"
  else
    EVIDENCE_TEXT="$EVIDENCE"
  fi
fi

# --- resolve cabinet root + actor ---
CABINET_ROOT="${CABINET_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
ACTOR="${OFFICER_NAME:-system}"

# --- map status to event_type ---
case "$STATUS" in
  done)     EVENT_TYPE="work_item_completed" ;;
  failed)   EVENT_TYPE="work_item_failed" ;;
  verified) EVENT_TYPE="work_item_verified" ;;
esac

# --- emit event via framework.events.emitter ---
# Build JSON payload safely via Python (handles escaping of EVIDENCE_TEXT)
PAYLOAD_JSON="$(NODE_ID="$NODE_ID" \
                OUTCOME_ID="$OUTCOME_ID" \
                TASK_INDEX="$TASK_INDEX" \
                STATUS="$STATUS" \
                EVIDENCE_TEXT="$EVIDENCE_TEXT" \
                EVIDENCE_PATH="$EVIDENCE_PATH" \
                python3 -c '
import json, os
print(json.dumps({
    "task_id": os.environ["NODE_ID"],
    "outcome_id": os.environ["OUTCOME_ID"],
    "task_index": int(os.environ["TASK_INDEX"]),
    "status": os.environ["STATUS"],
    "evidence_text": os.environ.get("EVIDENCE_TEXT") or None,
    "evidence_path": os.environ.get("EVIDENCE_PATH") or None,
}))
')"

EVENT_JSON="$(cd "$CABINET_ROOT" && python3 -m framework.events.emitter "$EVENT_TYPE" "$ACTOR" "$PAYLOAD_JSON")" || {
  echo "work-graph-complete: failed to emit $EVENT_TYPE event" >&2
  exit 1
}

# --- best-effort DB update ---
# If DATABASE_URL is set, also update the work_graph_nodes row. This isn't the
# source of truth (the event ledger is), but populating the DB makes OVI and
# downstream queries fast without replay.
if [[ -n "${DATABASE_URL:-}" ]]; then
  NODE_ID="$NODE_ID" \
  STATUS="$STATUS" \
  EVIDENCE_TEXT="$EVIDENCE_TEXT" \
  python3 - <<'PY' 2>&1 || echo "work-graph-complete: WARN db update failed (event still recorded)" >&2
import json
import os
import sys

node_id = os.environ["NODE_ID"]
status = os.environ["STATUS"]
evidence = os.environ.get("EVIDENCE_TEXT", "") or None

# Map our status to schema-allowed values (done|failed|verified are direct passthroughs)
status_db = status if status != "verified" else "done"  # schema only has 'done', 'failed'; verified is a separate event

try:
    import psycopg2
except ImportError:
    sys.exit(0)

try:
    conn = psycopg2.connect(os.environ["DATABASE_URL"])
    with conn.cursor() as cur:
        # work_graph_nodes.id is UUID; our task_id is a string. We store our
        # logical task_id in description prefix or via a side-channel. For now,
        # this update is a no-op unless a uuid-resolution layer is added in
        # Phase 1.2 (mission supervisor persists missions to DB).
        # This block is intentionally tolerant — the event is the truth.
        cur.execute(
            "UPDATE work_graph_nodes SET status = %s, completed_at = NOW(), evidence = %s "
            "WHERE description LIKE %s AND status != %s",
            (status_db, evidence, f"%{node_id}%", status_db),
        )
        rows = cur.rowcount
        conn.commit()
        if rows:
            print(f"work-graph-complete: updated {rows} work_graph_nodes row(s)", file=sys.stderr)
    conn.close()
except Exception as e:
    print(f"work-graph-complete: db update soft-failed: {e}", file=sys.stderr)
    sys.exit(0)
PY
fi

# --- print event id to stdout for chaining ---
echo "$EVENT_JSON" | python3 -c 'import json, sys; e = json.load(sys.stdin); print(e["id"])'
echo "work-graph-complete: ${EVENT_TYPE} emitted for ${NODE_ID} (status=${STATUS}, actor=${ACTOR})" >&2
