"""The disclosure ledger survived the redesign — checked against the tree it replaced.

WHAT THIS GUARDS. The onboarding card became a SCREEN ROUTER: one screen at a
time, one idea per screen, the honesty ledger folded rather than piled. Every
redesign of that shape has one way to go quietly wrong — a caveat that used to
be printed stops being emitted at all, and the product reads better precisely
because it now says less than it knows. Shorter is the goal; shorter by
DELETION is the failure, and the two are indistinguishable from the screen.

SO THE EXPECTED SET IS NOT WRITTEN BY HAND. ``data/disclosure-parity.json`` was
generated by running the PRE-CHANGE tree (the commit this branch forked from)
through every stage of a real journey and recording, per card: the section ids
it emitted, its body byte for byte, and its headline. The arms below assert the
post-change core still emits every one of those ids and the same body bytes.
A hand-written expectation would have been written by the same session that
wrote the code, from the same understanding, and would have agreed with it.

WHAT IT CANNOT PROVE, said plainly:
  * It compares the CORE's output. A row the core emits and no surface renders
    is invisible here — that arm is the dashboard's
    (``disclosure-render.test.ts``), which renders each screen and asserts every
    row's text is on it.
  * The volatile parts of a body (the temp source path, the charter
    fingerprint) are normalised to placeholders. Two different real paths would
    both normalise, so this arm proves the SENTENCE survived, not that the path
    in it is right — ``test_journey.py`` owns that.
  * It compares against one journey per stage. A row that only appears under
    inputs no fixture reaches is out of its coverage, and
    ``test_every_row_of_every_stage_is_wellformed`` is the partial answer: it
    holds for whatever rows the cards do produce.

Hermetic: tmp_path for every mutable root, fixture estates for every read.
"""
from __future__ import annotations

import json
import re
import shutil
from pathlib import Path

import pytest

from framework.onboarding import journey, research

REPO = Path(__file__).resolve().parents[3]
FIXTURES = REPO / "framework" / "onboarding" / "fixtures"
EXPECTED = json.loads(
    (Path(__file__).resolve().parent / "data" / "disclosure-parity.json")
    .read_text(encoding="utf-8")
)


# --- the same journeys the expectation was recorded from ---------------------


def _estate(root: Path, name: str) -> Path:
    target = root / "sources" / name
    shutil.copytree(FIXTURES / name, target)
    return target


def _seed(root: Path) -> dict:
    return journey.act(
        {"action": "answer_seed", "action_id": "seed-1", "surface": "dashboard",
         "seed": "I run a small inn on the coast", "purpose": "calmer bookings",
         "start_preference": "point"},
        root, now="2026-07-14T09:00:00Z")


def _propose(root: Path, source: Path) -> dict:
    return journey.act(
        {"action": "propose_window", "ownership": "self",
         "authority_basis": "my own machine, my own folder",
         "action_id": "propose-1", "surface": "dashboard", "source": str(source),
         "purpose": "Find one release risk before it surprises the team.",
         "relationship_destination": "reversible"},
        root, now="2026-07-14T10:00:00Z")


def _ratify(root: Path, proposed: dict) -> dict:
    return journey.act(
        {"action": "ratify_charter", "action_id": "ratify-1", "surface": "telegram",
         "charter_hash": proposed["state"]["charter"]["hash"],
         "expected_revision": proposed["state"]["revision"]},
        root, now="2026-07-14T10:00:03Z")


def _sweep_rows():
    return [
        {"connector": "tracker", "name": "Kaigan Ryokan", "updated": "2026-07-01",
         "actors": ["hanako.tanaka"]},
        {"connector": "tracker", "name": "yoyaku", "updated": "2026-07-02",
         "actors": ["buildbot"]},
        {"connector": "code", "name": "Kaigan Ryokan", "updated": "2026-07-03",
         "actors": ["htanaka"]},
        {"connector": "code", "name": "yoyaku", "updated": "2026-07-04",
         "actors": ["someone-else"]},
    ]


def _swept(root: Path) -> None:
    rows = _sweep_rows()
    state = journey._load_state(root)
    state["connector_sweep"] = {
        "schema": research.CONNECTOR_SWEEP_SCHEMA,
        "swept_at": "2026-07-14T09:30:00Z", "declared": 2, "calls": 2,
        "connectors": [
            {"name": "tracker", "connected": True, "items": 402, "calls": 1,
             "latest": "2026-07-02", "actors": 2},
            {"name": "code", "connected": True, "items": 264, "calls": 1,
             "latest": "2026-07-04", "actors": 2},
        ],
        "not_reached": [], "who_and_when": research.who_and_when(rows, {}),
    }
    state["salience_rows"] = {"schema": "cabinet.salience-rows/v1", "rows": rows,
                              "identities": [], "not_reached": []}
    journey._atomic_json(journey._state_path(root), state)


def _normalise(text: str, source_root: str) -> str:
    """The two volatile substrings, replaced exactly as the recorder replaced them."""
    out = str(text or "")
    if source_root:
        # The RESOLVED path, because macOS hands a temp dir back through a
        # symlink (/var -> /private/var) and the core prints the resolved one.
        out = out.replace(str(Path(source_root).resolve()), "<SOURCE>")
        out = out.replace(source_root, "<SOURCE>")
    return re.sub(r"(?<=fingerprint: )[0-9a-f]{12}", "<HASH>", out)


@pytest.fixture(scope="module")
def cards(tmp_path_factory) -> dict[str, dict]:
    """One card per recorded stage, from real journeys — never hand-built dicts."""
    out: dict[str, dict] = {}

    bare = tmp_path_factory.mktemp("bare")
    out["welcome_bare"] = {"card": journey.snapshot(bare)["card"], "source": ""}

    swept = tmp_path_factory.mktemp("swept")
    _seed(swept)
    _swept(swept)
    out["welcome_swept"] = {"card": journey.snapshot(swept)["card"], "source": ""}

    flow = tmp_path_factory.mktemp("flow")
    src = _estate(flow, "software-product")
    root = flow / "cabinet"
    root.mkdir()
    _seed(root)
    proposed = _propose(root, src)
    out["charter_pending"] = {"card": proposed["card"], "source": str(src)}
    ratified = _ratify(root, proposed)
    out["dividend_ready"] = {"card": ratified["card"], "source": str(src)}
    cont = journey.act(
        {"action": "continue", "action_id": "cont-1", "surface": "dashboard",
         "expected_revision": ratified["state"]["revision"]},
        root, now="2026-07-14T10:01:00Z")
    out["arrival"] = {"card": cont["card"], "source": str(src)}
    paused = journey.act(
        {"action": "pause", "action_id": "pause-1", "surface": "dashboard",
         "expected_revision": cont["state"]["revision"]},
        root, now="2026-07-14T10:02:00Z")
    out["paused"] = {"card": paused["card"], "source": str(src)}
    revoked = journey.act(
        {"action": "revoke", "action_id": "revoke-1", "surface": "dashboard",
         "expected_revision": paused["state"]["revision"]},
        root, now="2026-07-14T10:03:00Z")
    out["revoked"] = {"card": revoked["card"], "source": str(src)}
    purged = journey.act(
        {"action": "purge", "action_id": "purge-1", "surface": "dashboard",
         "confirmation": "PURGE",
         "expected_revision": revoked["state"]["revision"]},
        root, now="2026-07-14T10:04:00Z")
    out["purged"] = {"card": purged["card"], "source": str(src)}
    return out


# --- the parity check itself, as a function so it can be proven to fail -------


def assert_ids_survived(card: dict, expected_ids: list[str]) -> None:
    """Every disclosure id the pre-change tree emitted is still emitted.

    A FUNCTION, not an inline assert, precisely so the arm below can run it
    against a card with a row taken out and prove it goes red. A parity check
    that has never been shown to fail is a claim about a parity check.
    """
    emitted = {row["id"] for row in card.get("disclosures") or ()}
    missing = [row_id for row_id in expected_ids if row_id not in emitted]
    assert not missing, (
        f"disclosure rows the pre-change tree emitted and this one does not: {missing}. "
        "Shorter is the goal; shorter by deletion is the defect."
    )


def assert_body_survived(card: dict, expected_body: str, source_root: str) -> None:
    """The blob a non-folding surface renders is byte-for-byte what it was."""
    assert _normalise(card.get("body", ""), source_root) == expected_body


class TestEveryRecordedDisclosureSurvives:
    @pytest.mark.parametrize("name", sorted(EXPECTED))
    def test_every_pre_change_section_id_is_still_emitted(self, name, cards):
        assert_ids_survived(cards[name]["card"], EXPECTED[name]["section_ids"])

    @pytest.mark.parametrize("name", sorted(EXPECTED))
    def test_the_body_is_byte_for_byte_what_it_was(self, name, cards):
        """TELEGRAM AND EVERY OTHER NON-FOLDING SURFACE LOST NOTHING. The card
        stopped authoring a string and started authoring rows; the string is now
        their join, and this is the arm that says the join is the same string."""
        assert_body_survived(
            cards[name]["card"], EXPECTED[name]["body"], cards[name]["source"]
        )

    def test_the_id_parity_arm_fails_when_a_row_is_removed(self, cards):
        """THE SENSOR CAN FIRE. Take one row out of a real card and the check
        goes red — so a green run above is a measurement, not a tautology."""
        card = dict(cards["welcome_swept"]["card"])
        expected = EXPECTED["welcome_swept"]["section_ids"]
        card["disclosures"] = [
            row for row in card["disclosures"] if row["id"] != "cannot_know"
        ]
        with pytest.raises(AssertionError, match="cannot_know"):
            assert_ids_survived(card, expected)

    def test_the_body_parity_arm_fails_when_a_row_is_dropped_from_the_join(self, cards):
        """The same proof for the bytes: a body that drops one section's text is
        refused, so byte-equality above is measuring the join."""
        card = dict(cards["welcome_swept"]["card"])
        dropped = [row for row in card["disclosures"]
                   if row["layer"] != journey.DISCLOSURE_HEADLINE
                   and row["id"] != "probes"]
        card["body"] = "".join(row["text"] for row in dropped)
        with pytest.raises(AssertionError):
            assert_body_survived(card, EXPECTED["welcome_swept"]["body"], "")


class TestTheProjectionsAreViewsOfOneList:
    """``headline``/``details``/``body`` are DERIVED from ``disclosures``.

    The defect this closes is not hypothetical: the card used to author a
    headline list and a section list side by side, and nothing checked that a
    headline sentence was a sentence of the ledger it summarised.
    """

    @pytest.mark.parametrize("name", sorted(EXPECTED))
    def test_the_body_is_the_join_of_the_non_headline_rows(self, name, cards):
        card = cards[name]["card"]
        rest = [r for r in card["disclosures"]
                if r["layer"] != journey.DISCLOSURE_HEADLINE]
        assert card["body"] == "".join(r["text"] for r in rest)

    @pytest.mark.parametrize("name", sorted(EXPECTED))
    def test_details_are_exactly_the_non_headline_rows_in_order(self, name, cards):
        card = cards[name]["card"]
        rest = [r for r in card["disclosures"]
                if r["layer"] != journey.DISCLOSURE_HEADLINE]
        assert [d["id"] for d in card["details"]] == [r["id"] for r in rest]
        assert [d["text"] for d in card["details"]] == [r["text"] for r in rest]

    @pytest.mark.parametrize("name", sorted(EXPECTED))
    def test_the_headline_is_exactly_the_headline_rows(self, name, cards):
        card = cards[name]["card"]
        lead = [r["text"] for r in card["disclosures"]
                if r["layer"] == journey.DISCLOSURE_HEADLINE]
        assert card["headline"] == lead

    @pytest.mark.parametrize("name", sorted(EXPECTED))
    def test_every_row_of_every_stage_is_wellformed(self, name, cards):
        """A row with no layer, no text, or an unnamed fold is a row a surface
        cannot place. The degenerate end is checked here rather than assumed."""
        for row in cards[name]["card"]["disclosures"]:
            assert row["layer"] in journey.DISCLOSURE_LAYERS, row
            assert str(row["text"]).strip(), row
            assert isinstance(row["cites"], list), row
            if row["layer"] != journey.DISCLOSURE_HEADLINE:
                assert str(row["title"]).strip(), (
                    f"{row['id']} folds behind a heading, so it needs one"
                )

    @pytest.mark.parametrize("name", sorted(EXPECTED))
    def test_a_row_cites_only_citations_the_card_actually_carries(self, name, cards):
        """``cites`` REFERENCES ``card['evidence']``; it never copies it. A key
        that resolves to nothing would be a claim of receipts that do not
        exist — the exact shape of unsourced confidence this product refuses."""
        card = cards[name]["card"]
        available = {f"{c['path']}:{c['line']}" for c in card["evidence"]}
        for row in card["disclosures"]:
            for key in row["cites"]:
                assert key in available, (row["id"], key)

    def test_a_dividend_row_carries_the_citations_its_claim_rests_on(self, cards):
        """And the positive: the finding is the claim, so the finding is what
        cites. A citation list attached to nothing is decoration."""
        card = cards["dividend_ready"]["card"]
        assert card["evidence"], "the fixture estate yields a cited finding"
        finding = next(r for r in card["disclosures"] if r["id"] == "finding")
        assert len(finding["cites"]) == len(card["evidence"])


class TestTheHeadlineCeilingBites:
    """A CEILING SET WHERE THE BUILD FAILS IT (the ruling's rule for every new
    arm). Two, not three — and the pre-change tree emitted three on this exact
    journey, which is recorded in the fixture rather than asserted from memory.
    """

    def test_the_pre_change_tree_exceeded_the_ceiling_this_one_sets(self):
        assert len(EXPECTED["welcome_swept"]["headline"]) > journey.MAX_HEADLINE_LINES
        assert len(EXPECTED["arrival"]["headline"]) > journey.MAX_HEADLINE_LINES

    def test_more_candidates_are_composed_than_the_ceiling_admits(self, tmp_path):
        """The clip is real work, not a no-op: the composer still produces three
        candidate sentences and the ceiling drops the third."""
        _seed(tmp_path)
        _swept(tmp_path)
        state = journey._load_state(tmp_path)
        plan = journey._entry_plan_for(state)
        candidates = journey._entry_headline(state, plan)
        assert len(candidates) > journey.MAX_HEADLINE_LINES
        card = journey.snapshot(tmp_path)["card"]
        assert card["headline"] == candidates[:journey.MAX_HEADLINE_LINES]

    @pytest.mark.parametrize("name", sorted(EXPECTED))
    def test_no_card_exceeds_the_ceiling(self, name, cards):
        assert len(cards[name]["card"]["headline"]) <= journey.MAX_HEADLINE_LINES

    def test_a_clipped_candidate_leaves_the_disclosure_list_too(self, tmp_path):
        """A row that ships on the card and renders nowhere is a hidden row. The
        clip removes it from ``disclosures``, so what a surface receives is what
        a surface shows."""
        _seed(tmp_path)
        _swept(tmp_path)
        card = journey.snapshot(tmp_path)["card"]
        lead = [r for r in card["disclosures"]
                if r["layer"] == journey.DISCLOSURE_HEADLINE]
        assert len(lead) == journey.MAX_HEADLINE_LINES
        state = journey._load_state(tmp_path)
        dropped = journey._entry_headline(state, journey._entry_plan_for(state))[
            journey.MAX_HEADLINE_LINES:
        ]
        assert dropped, "this journey composes more candidates than the ceiling"
        assert all(text not in card["headline"] for text in dropped)


class TestTheConsentCardStatesItsFactsSeparately:
    """The approval screen inverts the layering — facts unfolded — which it can
    only do if the core hands it facts rather than a paragraph."""

    def test_the_charter_arrives_as_rows_a_screen_can_lay_out(self, cards):
        card = cards["charter_pending"]["card"]
        ids = [row["id"] for row in card["disclosures"]]
        for required in ("grant", "ownership", "limits", "fingerprint"):
            assert required in ids, ids

    def test_the_paragraph_it_replaces_is_still_exactly_reproducible(self, cards):
        """…and the surface that cannot lay them out reads the same paragraph."""
        assert_body_survived(
            cards["charter_pending"]["card"],
            EXPECTED["charter_pending"]["body"],
            cards["charter_pending"]["source"],
        )
