"""Sensors for the update path — cabinet-update.sh + lib/update_bundle.py.

WHAT IS UNDER TEST. An installed Cabinet is an unpacked export with no version
control in it. `cabinet-update.sh` is the only thing on such a box that can
take a landed improvement, and every one of its refusals is the whole boundary
there: the installed egg carries no filesystem flags, so the updater's parse of
the INSTALLED `germline-lock.sh` is the only thing standing between a bundle
and the constitutional set.

HOW THESE TESTS ARE BUILT, and why not with mocks. Each one provisions a REAL
fixture install (the real updater, the real helper, the real germline-lock.sh,
a real generated preserve set) and runs the real script end to end. The two
things that are stood in for are named and bounded:

  * the health gate's receipts and persistence legs ride their declared env
    seams, because a fixture install has no dashboard and no repository —
    `test_health_gate_defaults_are_the_contract_legs` pins what those commands
    are when nobody overrides them, so the seam cannot quietly become the
    behaviour;
  * `framework/` is symlinked in from the repo so the REAL emitter validates
    the three new event types. A stub emitter would have proved nothing about
    whether `cabinet_update_refused` is a registered type.

THE DEGENERATE END, checked deliberately. Absence is never a pass here: no
preserve declaration, an unparseable locked set, an empty bundle and a missing
manifest each get their own arm, because each one read as "go ahead" is exactly
the fail-open this path exists to avoid. Several arms carry an INVERTED twin
built from a MUTATED copy of the script (the re-exec stripped, the locked check
stripped) so the arm is proven to fail when the property is absent — a sensor
that passes in both directions is a disabled sensor.

Run: python3.12 -m pytest cabinet/scripts/tests/test_cabinet_update.py -q
"""

from __future__ import annotations

import fcntl
import json
import os
import re
import shutil
import signal
import subprocess
import sys
import tarfile
import time
from pathlib import Path

import pytest

_SCRIPTS_DIR = Path(__file__).resolve().parent.parent
_REPO_ROOT = _SCRIPTS_DIR.parent.parent
_UPDATER = _SCRIPTS_DIR / "cabinet-update.sh"
_BUNDLE_PY = _SCRIPTS_DIR / "lib" / "update_bundle.py"
_LOCK_SH = _SCRIPTS_DIR / "germline-lock.sh"
_PROVISION_SH = _SCRIPTS_DIR / "runtime-provision.sh"
_EXPORT_MANIFEST = _SCRIPTS_DIR / "egg-export-manifest.txt"

_PY = "python3.12"
_RUN_TIMEOUT = 180

sys.path.insert(0, str(_SCRIPTS_DIR / "lib"))
import update_bundle  # noqa: E402  (path set immediately above)


# ---------------------------------------------------------------------------
# fixture: a realistic installed Cabinet
# ---------------------------------------------------------------------------

OLD_SHA = "a" * 40
NEW_SHA = "b" * 40

#: The bytes every fixture bundle ships, keyed by repo-relative path. This is
#: the "shipped content" half of an install — the half an update may replace.
BASE_SHIPPED = {
    "cabinet/scripts/hello.sh": "echo hello v1\n",
    "cabinet/scripts/lib/helper.sh": "helper v1\n",
    "cabinet/docs/readme.md": "readme v1\n",
    "framework-note.txt": "note v1\n",
}


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def make_install(tmp_path: Path, *, source_commit: str = OLD_SHA) -> Path:
    """A fixture install: the real updater, the real boundary, real operator data."""

    root = tmp_path / "install"
    (root / "cabinet" / "scripts" / "lib").mkdir(parents=True)
    (root / "cabinet" / "config").mkdir(parents=True)

    shutil.copy2(_UPDATER, root / "cabinet" / "scripts" / "cabinet-update.sh")
    shutil.copy2(_BUNDLE_PY, root / "cabinet" / "scripts" / "lib" / "update_bundle.py")
    # The REAL boundary script — the locked-set parse is only worth anything
    # against the bytes it will actually meet.
    shutil.copy2(_LOCK_SH, root / "cabinet" / "scripts" / "germline-lock.sh")
    shutil.copy2(_PROVISION_SH, root / "cabinet" / "scripts" / "runtime-provision.sh")

    # The preserve set, generated by the same code path the export uses.
    _write(
        root / update_bundle.PRESERVE_SET_REL,
        update_bundle.preserve_set_document(_EXPORT_MANIFEST),
    )

    for rel, text in BASE_SHIPPED.items():
        _write(root / rel, text)

    # Operator data: never written, never deleted, never reported as content.
    _write(root / "instance/config/outcomes.yml", "outcomes:\n  - id: mine\n")
    _write(
        root / "shared/interfaces/captain-vetoes.yml",
        "version: 1\nnext_id: 2\nvetoes:\n  - id: 1\n    what: my own veto\n",
    )

    _write(
        root / "egg-manifest.json",
        json.dumps({"source_commit": source_commit, "cut_at": "2026-09-01T00:00:00Z"},
                   indent=2) + "\n",
    )

    # The real emitter, so the new event types are validated by the real
    # VALID_EVENT_TYPES rather than by a stub that would accept anything.
    os.symlink(_REPO_ROOT / "framework", root / "framework")
    return root


def make_bundle(
    tmp_path: Path,
    install_root: Path,
    sha: str,
    *,
    shipped: dict[str, str] | None = None,
    extra: dict[str, str] | None = None,
    built_at: str | None = None,
    changelog: list[str] | None = None,
    corrupt: bool = False,
    empty: bool = False,
) -> Path:
    """Cut a bundle into the install's inbox, the way `egg-export.sh --bundle` does."""

    tree = tmp_path / f"bundle-{sha[:12]}"
    if tree.exists():
        shutil.rmtree(tree)
    tree.mkdir(parents=True)

    if not empty:
        content = dict(BASE_SHIPPED if shipped is None else shipped)
        content.update(extra or {})
        for rel, text in content.items():
            _write(tree / rel, text)
        # A bundle is a cut of the same tree, so it carries the boundary script
        # and the generated preserve set exactly as the install has them.
        shutil.copy2(_LOCK_SH, tree / "cabinet/scripts/germline-lock.sh")
        _write(
            tree / update_bundle.PRESERVE_SET_REL,
            update_bundle.preserve_set_document(_EXPORT_MANIFEST),
        )
        shutil.copy2(_UPDATER, tree / "cabinet/scripts/cabinet-update.sh")
        shutil.copy2(_BUNDLE_PY, tree / "cabinet/scripts/lib/update_bundle.py")

    inbox = install_root / ".updates" / "inbox"
    inbox.mkdir(parents=True, exist_ok=True)
    manifest_path = inbox / f"{sha}.manifest.json"
    tar_path = inbox / f"{sha}.tar.gz"

    changelog_file = tmp_path / f"changelog-{sha[:12]}.txt"
    changelog_file.write_text("\n".join(changelog or ["a change"]) + "\n", encoding="utf-8")

    subprocess.run(
        [_PY, str(_BUNDLE_PY), "manifest", "--tree", str(tree), "--source-sha", sha,
         "--built-at", built_at or "2026-09-07T00:00:00Z",
         "--changelog-file", str(changelog_file), "--out", str(manifest_path)],
        check=True, capture_output=True, text=True,
    )
    with tarfile.open(tar_path, "w:gz") as tar:
        for child in sorted(tree.iterdir()):
            tar.add(child, arcname=child.name)
    if corrupt:
        # One shipped file's bytes no longer match its manifest digest.
        with tarfile.open(tar_path, "w:gz") as tar:
            (tree / "cabinet/scripts/hello.sh").write_text("tampered\n", encoding="utf-8")
            for child in sorted(tree.iterdir()):
                tar.add(child, arcname=child.name)
    return tree


def run_updater(
    install_root: Path,
    *args: str,
    env_extra: dict[str, str] | None = None,
    script: Path | None = None,
    timeout: int = _RUN_TIMEOUT,
) -> subprocess.CompletedProcess:
    env = dict(os.environ)
    env.update({
        "CABINET_ROOT": str(install_root),
        "CABINET_EVENT_LOG_DIR": str(install_root / ".events"),
        "PYTHONDONTWRITEBYTECODE": "1",
        # The gate's two non-dashboard legs, pointed at commands a fixture
        # install can actually run. `--skip-restart` makes the dashboard leg
        # THIN; the defaults are pinned by their own test below.
        "CABINET_UPDATE_RECEIPTS_CMD": "true",
        "CABINET_UPDATE_PREFLIGHT_CMD": "true",
        "CABINET_UPDATE_SKIP_DOCTOR": "1",
    })
    env.update(env_extra or {})
    target = script or (install_root / "cabinet" / "scripts" / "cabinet-update.sh")
    return subprocess.run(
        ["bash", str(target), *args],
        cwd=str(install_root), capture_output=True, text=True, timeout=timeout, env=env,
    )


def events(install_root: Path) -> list[dict]:
    out: list[dict] = []
    log_dir = install_root / ".events"
    if not log_dir.is_dir():
        return out
    for path in sorted(log_dir.glob("events-*.jsonl")):
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line:
                try:
                    out.append(json.loads(line))
                except ValueError:
                    pass
    return out


def event_types(install_root: Path) -> list[str]:
    return [e.get("event_type") or e.get("type") for e in events(install_root)]


def state(install_root: Path) -> dict:
    path = install_root / ".updates" / "state.json"
    return json.loads(path.read_text(encoding="utf-8")) if path.is_file() else {}


def installed_sha(install_root: Path) -> str:
    return json.loads((install_root / "egg-manifest.json").read_text())["source_commit"]


# ===========================================================================
# 1. the happy path, and what it must NOT have touched
# ===========================================================================

def test_apply_updates_code_and_preserves_instance(tmp_path):
    """A §5.1 / B §5.1: shipped code moves; the operator's own files do not."""
    root = make_install(tmp_path)
    make_bundle(tmp_path, root, NEW_SHA, extra={"cabinet/scripts/hello.sh": "echo hello v2\n"})

    outcomes_before = (root / "instance/config/outcomes.yml").read_bytes()
    vetoes_before = (root / "shared/interfaces/captain-vetoes.yml").read_bytes()

    result = run_updater(root, "apply", "--bundle", NEW_SHA, "--skip-rebuild", "--skip-restart")
    assert result.returncode == 0, result.stderr

    assert (root / "cabinet/scripts/hello.sh").read_text() == "echo hello v2\n"
    assert installed_sha(root) == NEW_SHA
    assert (root / "instance/config/outcomes.yml").read_bytes() == outcomes_before
    assert (root / "shared/interfaces/captain-vetoes.yml").read_bytes() == vetoes_before
    assert "cabinet_update_applied" in event_types(root)
    assert state(root)["phase"] == "applied"


def test_a_non_empty_veto_row_survives_an_apply(tmp_path):
    """A5.2: the live veto ledger is the operator's, even when a bundle ships one.

    The export ships this file HEADER-ONLY (`vetoes: []`), so a bundle always
    carries a copy — and an update that took the shipped copy would silently
    erase every veto the Captain had recorded. This is the arm that says the
    preserve set is doing real work rather than covering paths no bundle
    contains."""
    root = make_install(tmp_path)
    make_bundle(
        tmp_path, root, NEW_SHA,
        extra={"shared/interfaces/captain-vetoes.yml": "version: 1\nnext_id: 1\nvetoes: []\n"},
    )
    before = (root / "shared/interfaces/captain-vetoes.yml").read_text()
    assert "my own veto" in before

    result = run_updater(root, "apply", "--bundle", NEW_SHA, "--skip-rebuild", "--skip-restart")
    assert result.returncode == 0, result.stderr
    assert (root / "shared/interfaces/captain-vetoes.yml").read_text() == before


def test_apply_keeps_preserve_set_and_reports_the_skip(tmp_path):
    """A5.2: a bundle that CONTAINS a preserved path ⇒ skipped AND reported.

    Built on a bundle that ships one on purpose: a preserve test on a bundle
    with no preserved path in it passes against code that has no preserve set
    at all."""
    root = make_install(tmp_path)
    make_bundle(
        tmp_path, root, NEW_SHA,
        extra={
            "instance/config/outcomes.yml": "outcomes: []\n",
            "shared/interfaces/captain-vetoes.yml": "vetoes: []\n",
            "cabinet/scripts/hello.sh": "echo hello v2\n",
        },
    )
    result = run_updater(root, "apply", "--bundle", NEW_SHA, "--skip-rebuild", "--skip-restart")
    assert result.returncode == 0, result.stderr

    assert (root / "instance/config/outcomes.yml").read_text() == "outcomes:\n  - id: mine\n"
    skipped = state(root)["skipped_preserved"]
    assert "instance/config/outcomes.yml" in skipped
    assert "shared/interfaces/captain-vetoes.yml" in skipped
    # Reported, not silently dropped — on the record and on the operator's screen.
    applied = [e for e in events(root) if (e.get("event_type") or e.get("type")) == "cabinet_update_applied"]
    assert applied and "instance/config/outcomes.yml" in applied[-1]["payload"]["skipped_preserved"]
    assert "kept your own data" in result.stderr


def test_same_sha_is_a_noop_with_no_snapshot(tmp_path):
    """A §5.3 / B §5.1: the installed commit ⇒ exit 0, nothing written."""
    root = make_install(tmp_path, source_commit=NEW_SHA)
    make_bundle(tmp_path, root, NEW_SHA)
    result = run_updater(root, "apply", "--bundle", NEW_SHA, "--skip-rebuild", "--skip-restart")
    assert result.returncode == 0, result.stderr
    assert not (root / ".updates" / "snapshots").exists() or not list(
        (root / ".updates" / "snapshots").iterdir()
    )
    assert "cabinet_update_applied" not in event_types(root)


def test_identity_is_the_egg_manifest_and_no_version_file_is_written(tmp_path):
    """A5.3: `.cabinet-version` is cut; egg-manifest.json carries the identity."""
    root = make_install(tmp_path)
    make_bundle(tmp_path, root, NEW_SHA, extra={"cabinet/scripts/hello.sh": "v2\n"})
    run_updater(root, "apply", "--bundle", NEW_SHA, "--skip-rebuild", "--skip-restart")

    doc = json.loads((root / "egg-manifest.json").read_text())
    assert doc["source_commit"] == NEW_SHA
    assert doc["applied_at"]
    assert doc["applied_from"] == OLD_SHA
    assert not list(root.rglob(".cabinet-version"))
    # And no CODE line names one — both files mention it in a comment saying
    # exactly why a second identity file is not written, which is the sentence
    # a later reader needs and not a use.
    for path in (_UPDATER, _BUNDLE_PY):
        code = [line for line in path.read_text().splitlines()
                if ".cabinet-version" in line and not line.lstrip().startswith(("#", '"""'))]
        assert not code, (path.name, code)


# ===========================================================================
# 2. refusals — each one whole-bundle
# ===========================================================================

def test_refuses_locked_path_whole_bundle(tmp_path):
    """A §5.1 / B §5.3: any differing locked path ⇒ exit 3, nothing written."""
    root = make_install(tmp_path)
    tree = make_bundle(
        tmp_path, root, NEW_SHA,
        extra={"cabinet/scripts/hello.sh": "echo hello v2\n"},
    )
    # A locked FILE, changed by the bundle.
    (tree / "cabinet/scripts/germline-lock.sh").write_text(
        _LOCK_SH.read_text() + "\n# widened\n", encoding="utf-8"
    )
    make_bundle_refresh(tmp_path, root, NEW_SHA, tree)

    before = (root / "cabinet/scripts/hello.sh").read_text()
    result = run_updater(root, "apply", "--bundle", NEW_SHA, "--skip-rebuild", "--skip-restart")
    assert result.returncode == 3, (result.returncode, result.stderr)
    # WHOLE bundle: the unrelated, perfectly applicable file did not move.
    assert (root / "cabinet/scripts/hello.sh").read_text() == before
    assert installed_sha(root) == OLD_SHA
    assert "cabinet_update_refused" in event_types(root)
    assert "constitutional set" in result.stderr
    refused = [e for e in events(root)
               if (e.get("event_type") or e.get("type")) == "cabinet_update_refused"][-1]
    assert "cabinet/scripts/germline-lock.sh" in refused["payload"]["locked_paths"]


def make_bundle_refresh(tmp_path: Path, install_root: Path, sha: str, tree: Path) -> None:
    """Re-cut manifest + tarball after a test mutated a bundle tree in place."""
    inbox = install_root / ".updates" / "inbox"
    changelog_file = tmp_path / f"changelog-refresh-{sha[:12]}.txt"
    changelog_file.write_text("a change\n", encoding="utf-8")
    subprocess.run(
        [_PY, str(_BUNDLE_PY), "manifest", "--tree", str(tree), "--source-sha", sha,
         "--built-at", "2026-09-07T00:00:00Z", "--changelog-file", str(changelog_file),
         "--out", str(inbox / f"{sha}.manifest.json")],
        check=True, capture_output=True, text=True,
    )
    with tarfile.open(inbox / f"{sha}.tar.gz", "w:gz") as tar:
        for child in sorted(tree.iterdir()):
            tar.add(child, arcname=child.name)


def test_refuses_a_locked_DIRS_prefix_not_only_an_exact_file(tmp_path):
    """A5.4: DIRS entries match by PREFIX — the lock is applied with `chflags -R`.

    An exact-match parse would let every file under `cabinet/scripts/hooks/`
    through while reporting the boundary as enforced: a green hole, which is
    strictly worse than an open one."""
    root = make_install(tmp_path)
    _write(root / "cabinet/scripts/hooks/session-hook.py", "old hook\n")
    tree = make_bundle(
        tmp_path, root, NEW_SHA,
        extra={"cabinet/scripts/hooks/session-hook.py": "NEW HOOK\n"},
    )
    make_bundle_refresh(tmp_path, root, NEW_SHA, tree)

    result = run_updater(root, "apply", "--bundle", NEW_SHA, "--skip-rebuild", "--skip-restart")
    assert result.returncode == 3, (result.returncode, result.stderr)
    assert (root / "cabinet/scripts/hooks/session-hook.py").read_text() == "old hook\n"
    refused = [e for e in events(root)
               if (e.get("event_type") or e.get("type")) == "cabinet_update_refused"][-1]
    assert "cabinet/scripts/hooks/session-hook.py" in refused["payload"]["locked_paths"]


def test_a_locked_check_stripped_from_the_script_lets_the_bundle_through(tmp_path):
    """The INVERTED arm for the refusal above.

    Both refusal arms are red on master only because the script does not exist
    yet, which proves nothing about whether the check is wired. This one runs a
    MUTATED copy with the locked branch removed and asserts the bundle lands —
    so the two arms above are known to fail when the property is absent."""
    root = make_install(tmp_path)
    tree = make_bundle(tmp_path, root, NEW_SHA, extra={"cabinet/scripts/hello.sh": "v2\n"})
    (tree / "cabinet/scripts/germline-lock.sh").write_text(
        _LOCK_SH.read_text() + "\n# widened\n", encoding="utf-8"
    )
    make_bundle_refresh(tmp_path, root, NEW_SHA, tree)

    text = _UPDATER.read_text()
    marker = '  if [ "$locked_hits" != "[]" ]; then'
    assert marker in text, "the locked-hit branch moved; this inverted arm must be re-aimed"
    mutated_text = text.replace(marker, '  if false; then', 1)
    mutated = root / "cabinet" / "scripts" / "mutated-update.sh"
    mutated.write_text(mutated_text, encoding="utf-8")

    result = run_updater(root, "apply", "--bundle", NEW_SHA, "--skip-rebuild", "--skip-restart",
                         script=mutated)
    assert result.returncode == 0, result.stderr
    assert (root / "cabinet/scripts/hello.sh").read_text() == "v2\n"


def test_digest_mismatch_refuses(tmp_path):
    """B §5.4: a bundle whose bytes do not match its own manifest is refused."""
    root = make_install(tmp_path)
    make_bundle(tmp_path, root, NEW_SHA,
                extra={"cabinet/scripts/hello.sh": "echo hello v2\n"}, corrupt=True)
    result = run_updater(root, "apply", "--bundle", NEW_SHA, "--skip-rebuild", "--skip-restart")
    assert result.returncode == 3, (result.returncode, result.stderr)
    assert (root / "cabinet/scripts/hello.sh").read_text() == "echo hello v1\n"
    assert "cabinet_update_refused" in event_types(root)


def test_absent_and_empty_bundles_refuse(tmp_path):
    """B §5.7 degenerate end: absent, empty and unreadable are refusals."""
    root = make_install(tmp_path)
    missing = run_updater(root, "apply", "--bundle", NEW_SHA, "--skip-rebuild", "--skip-restart")
    assert missing.returncode == 3, missing.stderr

    inbox = root / ".updates" / "inbox"
    inbox.mkdir(parents=True, exist_ok=True)
    (inbox / f"{NEW_SHA}.manifest.json").write_text("{}", encoding="utf-8")
    (inbox / f"{NEW_SHA}.tar.gz").write_bytes(b"")
    empty = run_updater(root, "apply", "--bundle", NEW_SHA, "--skip-rebuild", "--skip-restart")
    assert empty.returncode == 3, empty.stderr
    assert installed_sha(root) == OLD_SHA


def test_no_preserve_declaration_on_either_side_refuses(tmp_path):
    """A5.2: absent on BOTH sides ⇒ refuse. An empty preserve set is not a pass."""
    root = make_install(tmp_path)
    (root / update_bundle.PRESERVE_SET_REL).unlink()
    tree = make_bundle(tmp_path, root, NEW_SHA, extra={"cabinet/scripts/hello.sh": "v2\n"})
    (tree / update_bundle.PRESERVE_SET_REL).unlink()
    make_bundle_refresh(tmp_path, root, NEW_SHA, tree)

    result = run_updater(root, "apply", "--bundle", NEW_SHA, "--skip-rebuild", "--skip-restart")
    assert result.returncode == 3, (result.returncode, result.stderr)
    assert (root / "cabinet/scripts/hello.sh").read_text() == "echo hello v1\n"


def test_unparseable_locked_set_refuses(tmp_path):
    """A5.4: unparseable or absent boundary ⇒ refuse, never "nothing is locked"."""
    root = make_install(tmp_path)
    make_bundle(tmp_path, root, NEW_SHA, extra={"cabinet/scripts/hello.sh": "v2\n"})
    (root / "cabinet/scripts/germline-lock.sh").write_text("#!/bin/bash\necho hi\n",
                                                           encoding="utf-8")
    result = run_updater(root, "apply", "--bundle", NEW_SHA, "--skip-rebuild", "--skip-restart")
    assert result.returncode == 3, (result.returncode, result.stderr)
    assert (root / "cabinet/scripts/hello.sh").read_text() == "echo hello v1\n"


def test_locked_set_parser_refuses_a_partial_parse(tmp_path):
    """The same property at the unit: a smaller boundary is not a boundary."""
    script = tmp_path / "germline-lock.sh"
    script.write_text(
        'FILES=(\n  "a/b.py"\n  unquoted/c.py\n)\nDIRS=(\n  "d/e"\n)\n', encoding="utf-8"
    )
    with pytest.raises(update_bundle.BundleError, match="parser drift"):
        update_bundle.parse_locked_set(script)


# ===========================================================================
# 3. deletions — manifest to manifest, never bundle to installed
# ===========================================================================

def test_first_apply_deletes_nothing(tmp_path):
    """A5.1: no applied manifest ⇒ the deletion set is empty, by construction.

    A bundle contains no `instance/` path at all (the export manifest deletes
    29 of them), so a bundle-versus-installed diff would mark the operator's
    entire instance tree for deletion. This arm is the one that would catch
    that rewrite."""
    root = make_install(tmp_path)
    _write(root / "cabinet/scripts/never-shipped-to-me.sh", "local\n")
    make_bundle(tmp_path, root, NEW_SHA, extra={"cabinet/scripts/hello.sh": "v2\n"})

    result = run_updater(root, "apply", "--bundle", NEW_SHA, "--skip-rebuild", "--skip-restart")
    assert result.returncode == 0, result.stderr
    assert state(root)["deleted"] == 0
    assert (root / "cabinet/scripts/never-shipped-to-me.sh").is_file()
    assert (root / "instance/config/outcomes.yml").is_file()
    assert (root / "instance/config").is_dir()


def test_second_apply_deletes_only_what_the_previous_bundle_shipped(tmp_path):
    """A5.1: deletions = previous manifest − new manifest, and nothing else."""
    root = make_install(tmp_path)
    _write(root / "cabinet/scripts/never-shipped-to-me.sh", "local\n")
    make_bundle(tmp_path, root, NEW_SHA,
                extra={"cabinet/scripts/retiring.sh": "goes away later\n"})
    assert run_updater(root, "apply", "--bundle", NEW_SHA,
                       "--skip-rebuild", "--skip-restart").returncode == 0
    assert (root / "cabinet/scripts/retiring.sh").is_file()

    third = "c" * 40
    make_bundle(tmp_path, root, third, built_at="2026-09-08T00:00:00Z")  # retiring.sh gone
    result = run_updater(root, "apply", "--bundle", third, "--skip-rebuild", "--skip-restart")
    assert result.returncode == 0, result.stderr
    assert not (root / "cabinet/scripts/retiring.sh").exists()
    assert (root / "cabinet/scripts/never-shipped-to-me.sh").is_file()
    assert (root / "instance/config/outcomes.yml").is_file()


# ===========================================================================
# 4. snapshots, rollback, pruning
# ===========================================================================

def test_rollback_restores_previous_and_keeps_three(tmp_path):
    """A §5.5 / B §5.3: rollback restores exactly; `CABINET_UPDATE_KEEP=3`."""
    root = make_install(tmp_path)
    original = (root / "cabinet/scripts/hello.sh").read_text()

    shas = ["b" * 40, "c" * 40, "d" * 40, "e" * 40, "f" * 40]
    for i, sha in enumerate(shas, start=2):
        make_bundle(tmp_path, root, sha,
                    extra={"cabinet/scripts/hello.sh": f"echo hello v{i}\n"},
                    built_at=f"2026-09-0{i}T00:00:00Z")
        result = run_updater(root, "apply", "--bundle", sha, "--skip-rebuild", "--skip-restart")
        assert result.returncode == 0, result.stderr

    snapshots = sorted(p.name for p in (root / ".updates" / "snapshots").iterdir())
    assert len(snapshots) == 3, snapshots
    assert (root / "cabinet/scripts/hello.sh").read_text() == "echo hello v6\n"

    back = run_updater(root, "rollback", "--skip-restart")
    assert back.returncode == 0, back.stderr
    assert (root / "cabinet/scripts/hello.sh").read_text() == "echo hello v5\n"
    assert installed_sha(root) == "e" * 40
    assert "cabinet_update_rolled_back" in event_types(root)
    assert original == "echo hello v1\n"


def test_rollback_removes_files_the_update_created(tmp_path):
    """A §5.5: "restores exactly the snapshot" includes what was not there before.

    A restore that only put bytes back would leave every newly-created file
    behind — a tree that is neither version."""
    root = make_install(tmp_path)
    make_bundle(tmp_path, root, NEW_SHA, extra={"cabinet/scripts/brand-new.sh": "new\n"})
    assert run_updater(root, "apply", "--bundle", NEW_SHA,
                       "--skip-rebuild", "--skip-restart").returncode == 0
    assert (root / "cabinet/scripts/brand-new.sh").is_file()

    assert run_updater(root, "rollback", "--skip-restart").returncode == 0
    assert not (root / "cabinet/scripts/brand-new.sh").exists()
    assert installed_sha(root) == OLD_SHA


def test_pruning_happens_only_after_a_green_gate(tmp_path):
    """A §5.5: an older snapshot is the only way back when the NEXT apply fails."""
    root = make_install(tmp_path)
    for i, sha in enumerate(["b" * 40, "c" * 40, "d" * 40], start=2):
        make_bundle(tmp_path, root, sha,
                    extra={"cabinet/scripts/hello.sh": f"echo hello v{i}\n"},
                    built_at=f"2026-09-0{i}T00:00:00Z")
        assert run_updater(root, "apply", "--bundle", sha,
                           "--skip-rebuild", "--skip-restart").returncode == 0
    assert len(list((root / ".updates" / "snapshots").iterdir())) == 3

    # A fourth apply whose gate is RED: it rolls itself back, and the three
    # snapshots that were there are all still there — nothing was pruned on the
    # strength of an apply that did not survive its own gate.
    make_bundle(tmp_path, root, "e" * 40,
                extra={"cabinet/scripts/hello.sh": "echo hello v5\n"},
                built_at="2026-09-05T00:00:00Z")
    result = run_updater(root, "apply", "--bundle", "e" * 40, "--skip-rebuild", "--skip-restart",
                         env_extra={"CABINET_UPDATE_RECEIPTS_CMD": "false"})
    assert result.returncode == 1, result.stderr
    assert len(list((root / ".updates" / "snapshots").iterdir())) == 4
    assert (root / "cabinet/scripts/hello.sh").read_text() == "echo hello v4\n"


# ===========================================================================
# 5. the health gate, and the automatic rollback
# ===========================================================================

def test_gate_red_rolls_back_and_the_gate_is_then_green(tmp_path):
    """A5.6: gate-red ⇒ rollback ⇒ gate-green, proved on the SAME gate command.

    The gate command here is a script the BUNDLE ships: the installed copy
    exits 0, the shipped copy exits 1. So the gate is red exactly because the
    new bytes are in place, and green again exactly because the rollback put
    the old ones back — rather than because the harness flipped a flag."""
    root = make_install(tmp_path)
    _write(root / "cabinet/scripts/fixture-gate.sh", "exit 0\n")
    make_bundle(tmp_path, root, NEW_SHA, extra={
        "cabinet/scripts/fixture-gate.sh": "exit 1\n",
        "cabinet/scripts/hello.sh": "echo hello v2\n",
    })
    gate_cmd = {"CABINET_UPDATE_RECEIPTS_CMD": "bash cabinet/scripts/fixture-gate.sh"}

    before = run_updater(root, "status")
    assert before.returncode == 0

    result = run_updater(root, "apply", "--bundle", NEW_SHA, "--skip-rebuild", "--skip-restart",
                         env_extra=gate_cmd)
    assert result.returncode == 1, (result.returncode, result.stderr)
    assert "cabinet_update_rolled_back" in event_types(root)
    assert state(root)["phase"] == "rolled_back"

    # The tree is the OLD one, and the very same gate command now passes.
    assert (root / "cabinet/scripts/hello.sh").read_text() == "echo hello v1\n"
    assert (root / "cabinet/scripts/fixture-gate.sh").read_text() == "exit 0\n"
    assert installed_sha(root) == OLD_SHA
    green = subprocess.run(["bash", "cabinet/scripts/fixture-gate.sh"], cwd=str(root))
    assert green.returncode == 0


def test_persistence_preflight_red_also_rolls_back(tmp_path):
    """A5.5: the preflight is one of the gate's legs, not a report."""
    root = make_install(tmp_path)
    make_bundle(tmp_path, root, NEW_SHA, extra={"cabinet/scripts/hello.sh": "v2\n"})
    result = run_updater(root, "apply", "--bundle", NEW_SHA, "--skip-rebuild", "--skip-restart",
                         env_extra={"CABINET_UPDATE_PREFLIGHT_CMD": "false"})
    assert result.returncode == 1, result.stderr
    assert (root / "cabinet/scripts/hello.sh").read_text() == "echo hello v1\n"
    assert installed_sha(root) == OLD_SHA


def test_health_gate_defaults_are_the_contract_legs(tmp_path):
    """The seams above are the harness; THIS is what runs when nobody overrides.

    Without this the two env variables would be free to become the behaviour —
    the "what does the test environment guarantee that production does not"
    question, asked of this file's own fixtures."""
    text = _UPDATER.read_text()
    assert "CABINET_UPDATE_RECEIPTS_CMD:-" in text
    assert "CABINET_UPDATE_PREFLIGHT_CMD:-" in text
    assert "state-persistence-preflight.py --repo ." in text
    assert "from framework.events.emitter import replay" in text
    # The dashboard leg checks BOTH the build stamp and the start time.
    assert "source_commit" in text and "started_at" in text
    assert "predates this update" in text
    # cabinet-doctor is reported, never gated.
    assert "REPORTED, never gated" in text


def test_doctor_is_reported_not_gated(tmp_path):
    """A §5: a doctor gate on a single-worker install would rollback-storm."""
    root = make_install(tmp_path)
    _write(root / "cabinet/scripts/cabinet-doctor.sh", "echo DEAD >&2\nexit 1\n")
    make_bundle(tmp_path, root, NEW_SHA, extra={"cabinet/scripts/hello.sh": "v2\n"})
    result = run_updater(root, "apply", "--bundle", NEW_SHA, "--skip-rebuild", "--skip-restart",
                         env_extra={"CABINET_UPDATE_SKIP_DOCTOR": "0"})
    assert result.returncode == 0, result.stderr
    assert installed_sha(root) == NEW_SHA
    assert "NOT a gate" in result.stderr


# ===========================================================================
# 6. interruption, the lock, and surviving the caller
# ===========================================================================

def test_kill_mid_apply_leaves_applying_and_the_next_call_restores_first(tmp_path):
    """A §5.4: a killed apply never reports done, and is put back before anything else."""
    root = make_install(tmp_path)
    make_bundle(tmp_path, root, NEW_SHA, extra={
        "cabinet/scripts/hello.sh": "echo hello v2\n",
        "cabinet/docs/readme.md": "readme v2\n",
        "framework-note.txt": "note v2\n",
    })
    killed = run_updater(root, "apply", "--bundle", NEW_SHA, "--skip-rebuild", "--skip-restart",
                         env_extra={"CABINET_UPDATE_TEST_KILL_AFTER": "1"})
    assert killed.returncode != 0
    assert state(root)["phase"] == "applying"
    assert state(root)["snapshot"]
    written = [rel for rel in ("cabinet/scripts/hello.sh", "cabinet/docs/readme.md",
                               "framework-note.txt")
               if "v2" in (root / rel).read_text()]
    assert 1 <= len(written) < 3, written  # genuinely mid-way

    # A rollback puts the interrupted tree back exactly.
    assert run_updater(root, "rollback", "--skip-restart").returncode == 0
    assert (root / "cabinet/scripts/hello.sh").read_text() == "echo hello v1\n"
    assert (root / "cabinet/docs/readme.md").read_text() == "readme v1\n"
    assert installed_sha(root) == OLD_SHA


def test_a_second_apply_after_a_kill_restores_before_it_applies(tmp_path):
    """The other half of A §5.4: apply also resumes, and then completes cleanly."""
    root = make_install(tmp_path)
    make_bundle(tmp_path, root, NEW_SHA, extra={
        "cabinet/scripts/hello.sh": "echo hello v2\n",
        "cabinet/docs/readme.md": "readme v2\n",
        "framework-note.txt": "note v2\n",
    })
    run_updater(root, "apply", "--bundle", NEW_SHA, "--skip-rebuild", "--skip-restart",
                env_extra={"CABINET_UPDATE_TEST_KILL_AFTER": "1"})
    assert state(root)["phase"] == "applying"

    again = run_updater(root, "apply", "--bundle", NEW_SHA, "--skip-rebuild", "--skip-restart")
    assert again.returncode == 0, again.stderr
    assert "restoring" in again.stderr
    assert (root / "cabinet/scripts/hello.sh").read_text() == "echo hello v2\n"
    assert (root / "cabinet/docs/readme.md").read_text() == "readme v2\n"
    assert (root / "framework-note.txt").read_text() == "note v2\n"
    assert installed_sha(root) == NEW_SHA
    assert state(root)["phase"] == "applied"


def test_a_second_updater_exits_busy(tmp_path):
    """A5.7: one updater at a time; the loser says so and emits a refusal."""
    root = make_install(tmp_path)
    make_bundle(tmp_path, root, NEW_SHA, extra={"cabinet/scripts/hello.sh": "v2\n"})
    (root / ".updates").mkdir(parents=True, exist_ok=True)
    holder = open(root / ".updates" / ".lock", "a+")
    fcntl.flock(holder.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
    try:
        result = run_updater(root, "apply", "--bundle", NEW_SHA,
                             "--skip-rebuild", "--skip-restart", timeout=60)
        assert result.returncode == 4, (result.returncode, result.stderr)
        assert (root / "cabinet/scripts/hello.sh").read_text() == "echo hello v1\n"
        refused = [e for e in events(root)
                   if (e.get("event_type") or e.get("type")) == "cabinet_update_refused"]
        assert refused and refused[-1]["payload"]["reason"] == "busy"
    finally:
        fcntl.flock(holder.fileno(), fcntl.LOCK_UN)
        holder.close()


def _launch_detached_apply(root: Path, sha: str, extra_env: dict[str, str]) -> subprocess.Popen:
    env = dict(os.environ)
    env.update({
        "CABINET_ROOT": str(root),
        "CABINET_EVENT_LOG_DIR": str(root / ".events"),
        "PYTHONDONTWRITEBYTECODE": "1",
        "CABINET_UPDATE_RECEIPTS_CMD": "true",
        "CABINET_UPDATE_PREFLIGHT_CMD": "true",
        "CABINET_UPDATE_SKIP_DOCTOR": "1",
    })
    env.update(extra_env)
    script = extra_env.pop("_SCRIPT", None) or str(root / "cabinet/scripts/cabinet-update.sh")
    # A launcher shell that backgrounds the updater and then sits — the stand-in
    # for the dashboard process the updater is about to restart. `start_new_session`
    # makes the launcher its own process-group leader so the kill below can take
    # the whole group and nothing else.
    return subprocess.Popen(
        ["bash", "-c",
         f'bash {script} apply --bundle {sha} --skip-rebuild --skip-restart >/dev/null 2>&1 &\n'
         f'sleep 120\n'],
        cwd=str(root), env=env, start_new_session=True,
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
    )


def _wait_for(predicate, seconds: float = 60.0) -> bool:
    deadline = time.time() + seconds
    while time.time() < deadline:
        if predicate():
            return True
        time.sleep(0.25)
    return predicate()


def test_updater_survives_the_death_of_the_process_that_spawned_it(tmp_path):
    """A5.8: the updater re-execs under a new session before its first write.

    It restarts the process that spawned it, so a signal aimed at that
    process's GROUP must not reach it. The kill below is a group kill, which is
    what a terminal hangup and a supervised job restart both are."""
    root = make_install(tmp_path)
    make_bundle(tmp_path, root, NEW_SHA, extra={"cabinet/scripts/hello.sh": "echo hello v2\n"})

    launcher = _launch_detached_apply(root, NEW_SHA, {"CABINET_UPDATE_TEST_HOLD_SECONDS": "5"})
    try:
        assert _wait_for(lambda: (root / ".updates" / "run" / "cabinet-update.sh").is_file(), 30), \
            "the updater never re-exec'd into .updates/run/"
        os.killpg(os.getpgid(launcher.pid), signal.SIGKILL)
        assert _wait_for(lambda: state(root).get("phase") == "applied", 90), state(root)
        assert (root / "cabinet/scripts/hello.sh").read_text() == "echo hello v2\n"
    finally:
        try:
            os.killpg(os.getpgid(launcher.pid), signal.SIGKILL)
        except (ProcessLookupError, PermissionError):
            pass
        launcher.wait(timeout=10)


def test_without_the_re_exec_the_group_kill_takes_the_updater_with_it(tmp_path):
    """The INVERTED arm: strip the new session and the property is gone.

    Without this, the arm above passes on any updater that merely finishes
    fast, and "survives its parent" would be an untested claim."""
    root = make_install(tmp_path)
    make_bundle(tmp_path, root, NEW_SHA, extra={"cabinet/scripts/hello.sh": "echo hello v2\n"})

    text = _UPDATER.read_text()
    marker = '  if command -v setsid >/dev/null 2>&1; then'
    assert marker in text, "the re-exec moved; this inverted arm must be re-aimed"
    mutated_text = text.replace(marker, '  if false; then', 1).replace(
        "os.setsid()", "pass  # session change removed for the inverted arm", 1)
    mutated = root / "cabinet" / "scripts" / "no-setsid-update.sh"
    mutated.write_text(mutated_text, encoding="utf-8")

    launcher = _launch_detached_apply(
        root, NEW_SHA,
        {"CABINET_UPDATE_TEST_HOLD_SECONDS": "8", "_SCRIPT": str(mutated)},
    )
    try:
        assert _wait_for(lambda: (root / ".updates" / "run" / "cabinet-update.sh").is_file(), 30)
        os.killpg(os.getpgid(launcher.pid), signal.SIGKILL)
        time.sleep(12)
        assert state(root).get("phase") != "applied", state(root)
        assert (root / "cabinet/scripts/hello.sh").read_text() == "echo hello v1\n"
    finally:
        try:
            os.killpg(os.getpgid(launcher.pid), signal.SIGKILL)
        except (ProcessLookupError, PermissionError):
            pass
        launcher.wait(timeout=10)


# ===========================================================================
# 7. the preserve set is DATA, and the two copies of it agree
# ===========================================================================

def test_preserve_set_parsed_not_copied(tmp_path):
    """A §5 sensor 4: no literal operator-data path list in the update path.

    The preserve set has ONE authoring source (the export manifest). A second
    copy typed into the updater is a second thing to keep in step, and the copy
    is always the one that goes stale."""
    literal = re.compile(r"""["']instance/""")
    for path in (_UPDATER, _BUNDLE_PY):
        offenders = [
            f"{path.name}:{i}: {line.strip()}"
            for i, line in enumerate(path.read_text().splitlines(), start=1)
            if literal.search(line)
        ]
        assert not offenders, offenders


def test_the_header_only_interface_set_matches_the_exporter(tmp_path):
    """The one place a second copy DOES exist — pinned so it cannot drift.

    `update_bundle.HEADER_ONLY_INTERFACES` and `egg-export.sh`'s closed
    `shared/interfaces` case list are two statements of the same fact. Two
    lists of one fact is a rule with a drift date; this is the date."""
    text = (_SCRIPTS_DIR / "egg-export.sh").read_text()
    body = text.split("t_interfaces_header_only()", 1)[1].split("\n}", 1)[0]
    from_exporter = set(re.findall(r"shared/interfaces/captain-[a-z-]+\.ya?ml", body))
    assert from_exporter, "the exporter's header-only set could not be read"
    assert from_exporter == set(update_bundle.HEADER_ONLY_INTERFACES)


def test_preserve_set_is_the_union_of_its_declared_sources(tmp_path):
    """A5.2: shipped file ∪ bundle copy ∪ `runtime-provision.sh lists` ∪ emptied."""
    root = make_install(tmp_path)
    entries = update_bundle.preserve_set(root)
    assert "instance/config/outcomes.yml" in entries          # export manifest rule
    assert "shared/interfaces/captain-vetoes.yml" in entries  # emptied at cut time

    provision = subprocess.run(
        ["bash", str(root / "cabinet/scripts/runtime-provision.sh"), "lists"],
        capture_output=True, text=True, check=True,
    )
    declared = [line.split(" ", 1)[1] for line in provision.stdout.splitlines() if " " in line]
    assert declared, "runtime-provision.sh lists printed nothing"
    for rel in declared:
        assert rel in entries, rel


def test_provision_lists_never_read_as_an_empty_list(tmp_path):
    """The degenerate end of the same parse."""
    script = tmp_path / "runtime-provision.sh"
    script.write_text("#!/bin/bash\necho hi\n", encoding="utf-8")
    with pytest.raises(update_bundle.BundleError, match="INSTANCE_PERSISTENT"):
        update_bundle.parse_provision_lists(script)


# ===========================================================================
# 8. status, publish and the doors
# ===========================================================================

def test_status_json_names_the_waiting_bundle_and_its_owner(tmp_path):
    """A5.11: the inbox is same-uid writable, so the card says who filled it."""
    root = make_install(tmp_path)
    make_bundle(tmp_path, root, NEW_SHA, extra={"cabinet/scripts/hello.sh": "v2\n"},
                changelog=["the tap now works", "gaps are recorded"])
    result = run_updater(root, "status", "--json")
    assert result.returncode == 0, result.stderr
    report = json.loads(result.stdout)
    assert report["installed_sha"] == OLD_SHA
    assert report["latest"]["sha"] == NEW_SHA
    assert report["latest"]["changelog"] == ["the tap now works", "gaps are recorded"]
    assert report["latest"]["owner"]
    assert report["latest"]["mtime"]


def test_status_says_nothing_is_waiting_when_the_inbox_matches_the_install(tmp_path):
    root = make_install(tmp_path, source_commit=NEW_SHA)
    make_bundle(tmp_path, root, NEW_SHA)
    report = json.loads(run_updater(root, "status", "--json").stdout)
    assert report["available"] == []
    assert report["latest"] is None


def test_the_terminal_door_never_claims_to_be_the_captain(tmp_path):
    """A0.1 + A1.2: door kinds are terminal | web | chat, and the terminal is
    attribution, not authentication — it is the same uid as every worker."""
    root = make_install(tmp_path)
    make_bundle(tmp_path, root, NEW_SHA, extra={"cabinet/scripts/hello.sh": "v2\n"})
    assert run_updater(root, "apply", "--bundle", NEW_SHA, "--skip-rebuild",
                       "--skip-restart", "--from", "terminal").returncode == 0
    applied = [e for e in events(root)
               if (e.get("event_type") or e.get("type")) == "cabinet_update_applied"][-1]
    assert applied["actor"] == "system"
    assert applied["payload"]["door"] == "terminal"

    root2 = make_install(tmp_path / "second")
    make_bundle(tmp_path / "second", root2, NEW_SHA, extra={"cabinet/scripts/hello.sh": "v2\n"})
    assert run_updater(root2, "apply", "--bundle", NEW_SHA, "--skip-rebuild",
                       "--skip-restart", "--from", "web").returncode == 0
    web = [e for e in events(root2)
           if (e.get("event_type") or e.get("type")) == "cabinet_update_applied"][-1]
    assert web["actor"] == "captain"
    assert web["payload"]["door"] == "web"


def test_no_vendor_noun_and_no_git_in_the_installed_root(tmp_path):
    """B §5.8 + the agnostic law: the updater runs no `git` against the install.

    `publish` is the producer side and runs `git` against a CLONE; every other
    subcommand runs on a box that has no repository at all."""
    text = _UPDATER.read_text()
    body = text.split("# ---- status", 1)[1]
    assert "git " not in body.replace("git -C \"$from\"", "")
    assert " launchctl " not in body  # restarts route through the dashboard library
    for noun in ("docker", "redis", "telegram", "github"):
        assert noun not in text.lower(), noun
        assert noun not in _BUNDLE_PY.read_text().lower(), noun


def test_publish_cuts_a_bundle_into_an_install_inbox(tmp_path):
    """A5.10: the producer step the landing lane runs, from a clone, after a merge."""
    root = make_install(tmp_path)
    result = subprocess.run(
        ["bash", str(_UPDATER), "publish", "--from", str(_REPO_ROOT), "--to", str(root)],
        capture_output=True, text=True, timeout=600,
        env={**os.environ, "CABINET_ROOT": str(root), "PYTHONDONTWRITEBYTECODE": "1"},
    )
    assert result.returncode == 0, result.stderr[-4000:]
    head = subprocess.run(["git", "-C", str(_REPO_ROOT), "rev-parse", "HEAD"],
                          capture_output=True, text=True, check=True).stdout.strip()
    manifest = root / ".updates" / "inbox" / f"{head}.manifest.json"
    assert manifest.is_file()
    doc = json.loads(manifest.read_text())
    assert doc["source_sha"] == head
    assert doc["files"], "the bundle manifest shipped no files"
    assert update_bundle.PRESERVE_SET_REL in doc["files"]
    assert "cabinet/scripts/cabinet-update.sh" in doc["files"]
    assert (root / ".updates" / "inbox" / f"{head}.tar.gz").stat().st_size > 0
    assert doc["from_sha"] == OLD_SHA


def test_publish_refuses_a_source_that_is_not_a_checkout(tmp_path):
    root = make_install(tmp_path)
    result = subprocess.run(
        ["bash", str(_UPDATER), "publish", "--from", str(tmp_path), "--to", str(root)],
        capture_output=True, text=True, timeout=60,
        env={**os.environ, "CABINET_ROOT": str(root)},
    )
    assert result.returncode == 3, (result.returncode, result.stderr)
